CREATE TABLE ATTORI(
	ID_ATTORE VARCHAR(6) PRIMARY KEY,
	NOMINATIVO VARCHAR(50) NOT NULL,
	NAZIONALITA VARCHAR(20) NOT NULL,
	DATA_NASCITA DATE NOT NULL
);

CREATE TABLE REGISTI(
	ID_REGISTA VARCHAR(6) PRIMARY KEY,
	NOMINATIVO VARCHAR(50) NOT NULL,
	NAZIONALITA VARCHAR(20) NOT NULL,
	DATA_NASCITA DATE NOT NULL
);

CREATE TABLE FILM(
	ID_FILM VARCHAR(6) PRIMARY KEY,
	TITOLO VARCHAR(50) NOT NULL,
	ANNO_PRODUZIONE VARCHAR(4) NOT NULL,
	ID_REGISTA VARCHAR(6),
	DURATAMIN SMALLINT NOT NULL ,
	
	CONSTRAINT CHECKDURATAMAX CHECK (DURATAMIN between 1 and 1440),
	CONSTRAINT CHECKANNO  CHECK  (CAST(ANNO_PRODUZIONE AS INTEGER) between 1895 and date_part('year', CURRENT_DATE)),
	CONSTRAINT FK_REGISTA FOREIGN KEY(ID_REGISTA) REFERENCES REGISTI(ID_REGISTA)
);

CREATE TABLE ATTORI_FILM(
	ID_ATTORE VARCHAR(6),
	ID_FILM  VARCHAR(8),
	
	CONSTRAINT FK_ATTOREFILM FOREIGN KEY(ID_ATTORE) REFERENCES ATTORI(ID_ATTORE),
	CONSTRAINT FK_FILMATTORE FOREIGN KEY(ID_FILM) REFERENCES FILM(ID_FILM)
);

CREATE TABLE SOUND_SYSTEM(
	ID_SOUND  varchar(4) PRIMARY KEY,
	ANNO varchar(4),
	NOME varchar(50)
);

CREATE TABLE GENERI(
	ID_GENERE  varchar(2) PRIMARY KEY,
	GENERE varchar(20)
);

CREATE TABLE GENERE_FILM(
	ID_GENERE  varchar(2) PRIMARY KEY,
	ID_FILM  VARCHAR(8),
	
	CONSTRAINT FK_GENEREFILM FOREIGN KEY(ID_GENERE) REFERENCES GENERI(ID_GENERE),
	CONSTRAINT FK_FILMGENERE FOREIGN KEY(ID_FILM) REFERENCES FILM(ID_FILM)
);


CREATE TABLE SALE(
	ID_SALA VARCHAR(3) PRIMARY KEY,
	DESCRIZIONE VARCHAR(20) NOT NULL,
	SOUND_SYSTEM VARCHAR(4),
	TECNOLOGIA VARCHAR(20),
	POSTI SMALLINT NOT NULL,
	
	CONSTRAINT CHECKPOSTIMAX CHECK (POSTI between 1 and 1000),
	CONSTRAINT FK_SOUND_SYSTEM FOREIGN KEY(ID_SALA) REFERENCES SOUND_SYSTEM(ID_SOUND)
);

CREATE TABLE PROIEZIONI(
	ID_PROIEZIONE VARCHAR(8) PRIMARY KEY,
	ID_SALA VARCHAR(3),
	ID_FILM  VARCHAR(8),
	DATA_PROIEZIONE DATE NOT NULL,
	INIZIO_PROIEZIONE TIME NOT NULL,
	FINE_PROIEZIONE TIME NOT NULL,
	
	CONSTRAINT FK_SALA FOREIGN KEY(ID_SALA) REFERENCES SALE(ID_SALA),
	CONSTRAINT FK_FILM FOREIGN KEY(ID_FILM) REFERENCES FILM(ID_FILM)
);

CREATE TABLE BIGLIETTI(
	ID_PROIEZIONE VARCHAR(8),
	ID_BIGLIETTO SERIAL PRIMARY KEY,
	PREZZO DECIMAL NOT NULL,
	SCONTO SMALLINT, 
	PREZZOFINALE DECIMAL NOT NULL,
	
	CONSTRAINT MAGGIORE_ZERO CHECK (PREZZO > 0 ),
	CONSTRAINT SCONTO_0_100 CHECK (SCONTO between 0 and 100),
	CONSTRAINT PREZZO_FINALE_CONCORDE CHECK (PREZZOFINALE <= PREZZO AND PREZZOFINALE = PREZZO-(PREZZO*SCONTO/100)),
	CONSTRAINT FK_SALA FOREIGN KEY(ID_PROIEZIONE) REFERENCES PROIEZIONI(ID_PROIEZIONE)
);



CREATE VIEW SPETTACOLI_RENUMERATIVI AS (
	SELECT (SELECT F.TITOLO FROM FILM F WHERE F.ID_FILM=P.ID_FILM)FILM,COUNT(B.ID_BIGLIETTO)BIGLIETTI_VENDUTI,SUM(B.PREZZOFINALE)GUADAGNO_TOTALE
	FROM BIGLIETTI B JOIN PROIEZIONI P 
	ON B.ID_PROIEZIONE=P.ID_PROIEZIONE
	GROUP BY FILM
);