DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE PAESI(
	ID_PAESE SMALLSERIAL PRIMARY KEY,
	PAESE VARCHAR(60) UNIQUE
);

CREATE TABLE SISTEMI_AUDIO(
	ID_SOUND SMALLSERIAL PRIMARY KEY,
	ANNO VARCHAR(4),
	AUDIO VARCHAR(50) UNIQUE
);

CREATE TABLE TECNOLOGIE_PROIEZIONE(
	ID_TEC SMALLSERIAL PRIMARY KEY,
	ANNO VARCHAR(4),
	TECNOLOGIA VARCHAR(50) UNIQUE
);

CREATE TABLE GENERI(
	ID_GENERE  SMALLSERIAL PRIMARY KEY,
	GENERE VARCHAR(20) UNIQUE
);

CREATE TABLE ATTORI(
	ID_ATTORE SERIAL PRIMARY KEY,
	NOMINATIVO VARCHAR(50) NOT NULL,
	PAESE_DI_ORIGINE VARCHAR(30),
	DATA_NASCITA DATE,
	
	CONSTRAINT DATA_NASCITA_CONCORDE CHECK (DATA_NASCITA < CURRENT_DATE),
	CONSTRAINT SOLO_LETTERE CHECK ((NOMINATIVO ~* '[0-9]') is false)	
);

CREATE TABLE REGISTI(
	ID_REGISTA SERIAL PRIMARY KEY,
	NOMINATIVO VARCHAR(50) NOT NULL,
	PAESE_DI_ORIGINE VARCHAR(20) NOT NULL,
	DATA_NASCITA DATE NOT NULL,
	
	CONSTRAINT DATA_NASCITA_CONCORDE CHECK (DATA_NASCITA < CURRENT_DATE),
	CONSTRAINT SOLO_LETTERE CHECK ((NOMINATIVO ~* '[0-9]') is false)
);

CREATE TABLE FILM(
	ID_FILM SERIAL PRIMARY KEY,
	TITOLO VARCHAR(100) NOT NULL,
	ANNO_PRODUZIONE VARCHAR(4) NOT NULL,
	ID_REGISTA INTEGER,
	DURATA_MINUTI SMALLINT NOT NULL ,
	URL_POSTER VARCHAR(500) ,
	
	CONSTRAINT CHECKDURATAMAX CHECK (DURATA_MINUTI BETWEEN 1 AND 1440),
	CONSTRAINT CHECKANNO  CHECK  (CAST(ANNO_PRODUZIONE AS INTEGER) BETWEEN 1895 AND DATE_PART('YEAR', CURRENT_DATE)),
	CONSTRAINT FK_REGISTA FOREIGN KEY(ID_REGISTA) REFERENCES REGISTI(ID_REGISTA) 
);

CREATE TABLE ATTORI_FILM(
	ID_ATTORE INTEGER,
	ID_FILM  INTEGER,
	
	CONSTRAINT PK_ATTORI_FILM PRIMARY KEY(ID_ATTORE,ID_FILM),
	CONSTRAINT FK_ATTOREFILM FOREIGN KEY(ID_ATTORE) REFERENCES ATTORI(ID_ATTORE),
	CONSTRAINT FK_FILMATTORE FOREIGN KEY(ID_FILM) REFERENCES FILM(ID_FILM)
);


CREATE TABLE GENERE_FILM(
	ID_GENERE  INTEGER,
	ID_FILM  INTEGER,
	
	CONSTRAINT PK_GENERE_FILM PRIMARY KEY(ID_GENERE,ID_FILM),
	CONSTRAINT FK_GENEREFILM FOREIGN KEY(ID_GENERE) REFERENCES GENERI(ID_GENERE),
	CONSTRAINT FK_FILMGENERE FOREIGN KEY(ID_FILM) REFERENCES FILM(ID_FILM)
);


CREATE TABLE SALE(
	ID_SALA SERIAL PRIMARY KEY,
	DESCRIZIONE VARCHAR(20) NOT NULL,
	SISTEMA_AUDIO VARCHAR(4),
	TECNOLOGIA_PROIEZIONE VARCHAR(20),
	POSTI SMALLINT NOT NULL,
	
	CONSTRAINT CHECKPOSTIMAX CHECK (POSTI BETWEEN 1 AND 500)
);

CREATE TABLE PROIEZIONI(
	ID_PROIEZIONE SERIAL PRIMARY KEY,
	ID_SALA INTEGER,
	ID_FILM  INTEGER,
	PREZZO DECIMAL NOT NULL,
	INIZIO_PROIEZIONE TIMESTAMP NOT NULL,
	FINE_PROIEZIONE TIMESTAMP NOT NULL,

	CONSTRAINT MAGGIORE_ZERO CHECK (PREZZO > 0 ),	
	CONSTRAINT FK_SALA FOREIGN KEY(ID_SALA) REFERENCES SALE(ID_SALA),
	CONSTRAINT FK_FILM FOREIGN KEY(ID_FILM) REFERENCES FILM(ID_FILM) ON DELETE CASCADE,
	CONSTRAINT ORARI_CONCORDI CHECK (INIZIO_PROIEZIONE < FINE_PROIEZIONE),
	CONSTRAINT INIZIO_FINE_NO24H CHECK ((DATE_PART('day', FINE_PROIEZIONE::timestamp - INIZIO_PROIEZIONE::timestamp) * 24 + DATE_PART('hour', FINE_PROIEZIONE::timestamp - INIZIO_PROIEZIONE::timestamp))<=24)
);

CREATE TABLE BIGLIETTI(
	ID_PROIEZIONE INTEGER,
	ID_BIGLIETTO SERIAL PRIMARY KEY,
	SCONTO SMALLINT, 
	PREZZOFINALE DECIMAL NOT NULL,
	
	CONSTRAINT SCONTO_0_100 CHECK (SCONTO BETWEEN 0 AND 100),
	CONSTRAINT FK_PROIEZIONE FOREIGN KEY(ID_PROIEZIONE) REFERENCES PROIEZIONI(ID_PROIEZIONE) ON DELETE CASCADE
);



CREATE VIEW SPETTACOLI_RENUMERATIVI AS (
	SELECT (SELECT F.TITOLO FROM FILM F WHERE F.ID_FILM=P.ID_FILM)FILM,COUNT(B.ID_BIGLIETTO)BIGLIETTI_VENDUTI,SUM(B.PREZZOFINALE)GUADAGNO_TOTALE
	FROM BIGLIETTI B JOIN PROIEZIONI P 
	ON B.ID_PROIEZIONE=P.ID_PROIEZIONE
	GROUP BY FILM
	ORDER BY BIGLIETTI_VENDUTI,GUADAGNO_TOTALE
	
);

CREATE VIEW ORARI_MAGGIORE_AFFLUENZA AS (
	SELECT COUNT(*)AFFLUENZA,CAST(INIZIO_PROIEZIONE AS TIME)FASCIAINIZIO,CAST(FINE_PROIEZIONE AS TIME)FASCIAFINE
	FROM BIGLIETTI B JOIN PROIEZIONI P 
	ON B.ID_PROIEZIONE=P.ID_PROIEZIONE
	GROUP BY FASCIAINIZIO,FASCIAFINE
	ORDER BY AFFLUENZA DESC
);

CREATE VIEW AFFLUENZA_SALE_ORARI_MAX AS (
	SELECT	COUNT(*)CONTA,P.ID_SALA,CAST(P.INIZIO_PROIEZIONE AS TIME)FASCIAINIZIO,CAST(P.FINE_PROIEZIONE AS TIME)FASCIAFINE
	FROM BIGLIETTI B JOIN PROIEZIONI P
	ON B.ID_PROIEZIONE=P.ID_PROIEZIONE
	GROUP BY 2,3,4
	HAVING CAST(P.INIZIO_PROIEZIONE AS TIME)||'-'||CAST(P.FINE_PROIEZIONE AS TIME) IN (SELECT O.FASCIAINIZIO||'-'||O.FASCIAFINE FROM ORARI_MAGGIORE_AFFLUENZA O WHERE O.AFFLUENZA=(SELECT MAX(O.AFFLUENZA) FROM ORARI_MAGGIORE_AFFLUENZA O))
	ORDER BY CONTA DESC
);


/*TRIGGERS*/
/*CONTROLLO SALA*/
CREATE OR REPLACE FUNCTION  CONTROLLO_SALA_PIENA() 
RETURNS TRIGGER AS $$    
DECLARE
   POSTI_SALA INT;
   BIGLIETTI_VENDUTI INT;
BEGIN
	SELECT S.POSTI INTO POSTI_SALA FROM SALE S WHERE S.ID_SALA=(SELECT P.ID_SALA FROM PROIEZIONI P WHERE P.ID_PROIEZIONE=NEW.ID_PROIEZIONE);
	SELECT COUNT(*) INTO BIGLIETTI_VENDUTI FROM BIGLIETTI B WHERE B.ID_PROIEZIONE=NEW.ID_PROIEZIONE;
	IF (POSTI_SALA = BIGLIETTI_VENDUTI) THEN 
		RAISE EXCEPTION 'SALA PIENA';
	END IF;
	RETURN NEW;
END; 
$$ language plpgsql;

/*CONTROLLO PROIEZIONE*/
CREATE OR REPLACE FUNCTION CONTROLLO_SALA_FILM_ORARIO() 
RETURNS TRIGGER AS $$ 
DECLARE
   CONTA INT := 0;
   RIGA PROIEZIONI%ROWTYPE;
BEGIN
	FOR RIGA IN SELECT * FROM PROIEZIONI P 
	WHERE P.ID_SALA=NEW.ID_SALA AND 
		  (P.INIZIO_PROIEZIONE::DATE IN (P.INIZIO_PROIEZIONE::DATE,P.FINE_PROIEZIONE::DATE) OR
		  P.FINE_PROIEZIONE::DATE IN (P.INIZIO_PROIEZIONE::DATE,P.FINE_PROIEZIONE::DATE))
	LOOP
		IF((NEW.INIZIO_PROIEZIONE BETWEEN RIGA.INIZIO_PROIEZIONE AND RIGA.FINE_PROIEZIONE) 
		   OR (NEW.FINE_PROIEZIONE BETWEEN RIGA.INIZIO_PROIEZIONE AND RIGA.FINE_PROIEZIONE)) THEN
			CONTA := CONTA + 1;
		END IF;
		EXIT WHEN CONTA > 0;
	END LOOP;
	IF(CONTA > 0) THEN
		RAISE EXCEPTION 'SALA GIÀ OCCUPATA PER LA DATA E L''ORARIO INSERITO';
	END IF;
	RETURN NEW;
END; 
$$ language plpgsql;

/*CONTROLLO PROIEZIONE*/
CREATE OR REPLACE FUNCTION CONTROLLO_PROIEZIONE_DURATA_FILM() 
RETURNS TRIGGER AS $$ 
DECLARE
   MINUTI_FILM INT := 0;
BEGIN
	SELECT F.DURATA_MINUTI INTO MINUTI_FILM FROM FILM F WHERE F.ID_FILM=NEW.ID_FILM;
	IF(((DATE_PART('DAY', CAST(NEW.FINE_PROIEZIONE AS timestamp ) - CAST(NEW.INIZIO_PROIEZIONE AS timestamp )) * 24 + 
               DATE_PART('HOUR', CAST(NEW.FINE_PROIEZIONE AS timestamp ) - CAST(NEW.INIZIO_PROIEZIONE AS timestamp ))) * 60 +
               DATE_PART('MINUTE', CAST(NEW.FINE_PROIEZIONE AS timestamp ) - CAST(NEW.INIZIO_PROIEZIONE AS timestamp ))) < MINUTI_FILM) THEN
		RAISE EXCEPTION 'LA DURATA DEL FILM É MAGGIORE RISPETTO ALLA DURATA DELLA PROIEZIONE ';
	END IF;
	RETURN NEW;
END; 
$$ language plpgsql;

/*CONTROLLO BIGLIETTI*/
CREATE OR REPLACE FUNCTION CONTROLLO_SCONTO_PREZZO_FINALE() 
RETURNS TRIGGER AS $$ 
DECLARE
   PREZZO_PROIEZIONE INT := 0;
BEGIN
	SELECT P.PREZZO INTO PREZZO_PROIEZIONE FROM PROIEZIONI P WHERE P.ID_PROIEZIONE=NEW.ID_PROIEZIONE;
	IF(PREZZO_PROIEZIONE-(PREZZO_PROIEZIONE*NEW.SCONTO)/100 <> NEW.PREZZOFINALE) THEN
		RAISE EXCEPTION 'PREZZOFINALE BIGLIETTO NON COERENTE CON SCONTO APPLICATO';
	END IF;
	RETURN NEW;
END; 
$$ language plpgsql;

CREATE TRIGGER MIN_PROIEZIONE_CONCORDE_CON_MIN_FILM
BEFORE INSERT
ON PROIEZIONI
FOR EACH ROW
EXECUTE FUNCTION CONTROLLO_PROIEZIONE_DURATA_FILM();

CREATE TRIGGER SALA_PIENA
BEFORE INSERT
ON BIGLIETTI
FOR EACH ROW
EXECUTE FUNCTION CONTROLLO_SALA_PIENA();

CREATE TRIGGER PROIEZIONE_NON_POSSIBILE
BEFORE INSERT
ON PROIEZIONI
FOR EACH ROW
EXECUTE FUNCTION CONTROLLO_SALA_FILM_ORARIO();

CREATE TRIGGER SCONTO_COERENTE_CON_PREZZO_FINALE
BEFORE INSERT
ON BIGLIETTI
FOR EACH ROW
EXECUTE FUNCTION CONTROLLO_SCONTO_PREZZO_FINALE();