INSERT INTO paesi(paese)VALUES ('Afghanistan');
INSERT INTO paesi(paese)VALUES ('Albania');
INSERT INTO paesi(paese)VALUES ('Algeria');
INSERT INTO paesi(paese)VALUES ('Andorra');
INSERT INTO paesi(paese)VALUES ('Angola');
INSERT INTO paesi(paese)VALUES ('Antigua e Barbuda');
INSERT INTO paesi(paese)VALUES ('Apolide');
INSERT INTO paesi(paese)VALUES ('Arabia Saudita');
INSERT INTO paesi(paese)VALUES ('Argentina');
INSERT INTO paesi(paese)VALUES ('Armenia');
INSERT INTO paesi(paese)VALUES ('Australia');
INSERT INTO paesi(paese)VALUES ('Austria');
INSERT INTO paesi(paese)VALUES ('Azerbaigian');
INSERT INTO paesi(paese)VALUES ('Bahamas');
INSERT INTO paesi(paese)VALUES ('Bahrein');
INSERT INTO paesi(paese)VALUES ('Bangladesh');
INSERT INTO paesi(paese)VALUES ('Barbados');
INSERT INTO paesi(paese)VALUES ('Belgio');
INSERT INTO paesi(paese)VALUES ('Belize');
INSERT INTO paesi(paese)VALUES ('Benin (ex Dahomey)');
INSERT INTO paesi(paese)VALUES ('Bhutan');
INSERT INTO paesi(paese)VALUES ('Bielorussia');
INSERT INTO paesi(paese)VALUES ('Bolivia');
INSERT INTO paesi(paese)VALUES ('Bosnia-Erzegovina');
INSERT INTO paesi(paese)VALUES ('Botswana');
INSERT INTO paesi(paese)VALUES ('Brasile');
INSERT INTO paesi(paese)VALUES ('Brunei');
INSERT INTO paesi(paese)VALUES ('Bulgaria');
INSERT INTO paesi(paese)VALUES ('Burkina Faso (ex Alto Volta)');
INSERT INTO paesi(paese)VALUES ('Burundi');
INSERT INTO paesi(paese)VALUES ('Cambogia');
INSERT INTO paesi(paese)VALUES ('Camerun');
INSERT INTO paesi(paese)VALUES ('Canada');
INSERT INTO paesi(paese)VALUES ('Capo Verde');
INSERT INTO paesi(paese)VALUES ('Centrafricana, Repubblica');
INSERT INTO paesi(paese)VALUES ('Ciad');
INSERT INTO paesi(paese)VALUES ('Cile');
INSERT INTO paesi(paese)VALUES ('Cinese, Repubblica Popolare');
INSERT INTO paesi(paese)VALUES ('Cipro');
INSERT INTO paesi(paese)VALUES ('Colombia');
INSERT INTO paesi(paese)VALUES ('Comore');
INSERT INTO paesi(paese)VALUES ('Congo');
INSERT INTO paesi(paese)VALUES ('Congo, Repubblica democratica del (ex Zaire)');
INSERT INTO paesi(paese)VALUES ('Corea, Repubblica (Corea del Sud)');
INSERT INTO paesi(paese)VALUES ('Corea, Repubblica Popolare Democratica (Corea del Nord)');
INSERT INTO paesi(paese)VALUES ('Costa Rica');
INSERT INTO paesi(paese)VALUES ('Costa d''Avorio');
INSERT INTO paesi(paese)VALUES ('Croazia');
INSERT INTO paesi(paese)VALUES ('Cuba');
INSERT INTO paesi(paese)VALUES ('Danimarca');
INSERT INTO paesi(paese)VALUES ('Dominica');
INSERT INTO paesi(paese)VALUES ('Dominicana, Repubblica');
INSERT INTO paesi(paese)VALUES ('Ecuador');
INSERT INTO paesi(paese)VALUES ('Egitto');
INSERT INTO paesi(paese)VALUES ('El Salvador');
INSERT INTO paesi(paese)VALUES ('Emirati Arabi Uniti');
INSERT INTO paesi(paese)VALUES ('Eritrea');
INSERT INTO paesi(paese)VALUES ('Estonia');
INSERT INTO paesi(paese)VALUES ('Etiopia');
INSERT INTO paesi(paese)VALUES ('Figi');
INSERT INTO paesi(paese)VALUES ('Filippine');
INSERT INTO paesi(paese)VALUES ('Finlandia');
INSERT INTO paesi(paese)VALUES ('Francia');
INSERT INTO paesi(paese)VALUES ('Gabon');
INSERT INTO paesi(paese)VALUES ('Gambia');
INSERT INTO paesi(paese)VALUES ('Georgia');
INSERT INTO paesi(paese)VALUES ('Germania');
INSERT INTO paesi(paese)VALUES ('Ghana');
INSERT INTO paesi(paese)VALUES ('Giamaica');
INSERT INTO paesi(paese)VALUES ('Giappone');
INSERT INTO paesi(paese)VALUES ('Gibuti');
INSERT INTO paesi(paese)VALUES ('Giordania');
INSERT INTO paesi(paese)VALUES ('Grecia');
INSERT INTO paesi(paese)VALUES ('Grenada');
INSERT INTO paesi(paese)VALUES ('Guatemala');
INSERT INTO paesi(paese)VALUES ('Guinea');
INSERT INTO paesi(paese)VALUES ('Guinea Bissau');
INSERT INTO paesi(paese)VALUES ('Guinea Equatoriale');
INSERT INTO paesi(paese)VALUES ('Guyana');
INSERT INTO paesi(paese)VALUES ('Haiti');
INSERT INTO paesi(paese)VALUES ('Honduras');
INSERT INTO paesi(paese)VALUES ('India');
INSERT INTO paesi(paese)VALUES ('Indonesia');
INSERT INTO paesi(paese)VALUES ('Iran, Repubblica Islamica del');
INSERT INTO paesi(paese)VALUES ('Iraq');
INSERT INTO paesi(paese)VALUES ('Irlanda');
INSERT INTO paesi(paese)VALUES ('Islanda');
INSERT INTO paesi(paese)VALUES ('Israele');
INSERT INTO paesi(paese)VALUES ('Jersey, Isole*');
INSERT INTO paesi(paese)VALUES ('Kazakhstan');
INSERT INTO paesi(paese)VALUES ('Kenya');
INSERT INTO paesi(paese)VALUES ('Kirghizistan');
INSERT INTO paesi(paese)VALUES ('Kiribati');
INSERT INTO paesi(paese)VALUES ('Kosovo');
INSERT INTO paesi(paese)VALUES ('Kuwait');
INSERT INTO paesi(paese)VALUES ('Laos');
INSERT INTO paesi(paese)VALUES ('Lesotho');
INSERT INTO paesi(paese)VALUES ('Lettonia');
INSERT INTO paesi(paese)VALUES ('Libano');
INSERT INTO paesi(paese)VALUES ('Liberia');
INSERT INTO paesi(paese)VALUES ('Libia');
INSERT INTO paesi(paese)VALUES ('Liechtenstein');
INSERT INTO paesi(paese)VALUES ('Lituania');
INSERT INTO paesi(paese)VALUES ('Lussemburgo');
INSERT INTO paesi(paese)VALUES ('Macedonia, Repubblica di');
INSERT INTO paesi(paese)VALUES ('Madagascar');
INSERT INTO paesi(paese)VALUES ('Malawi');
INSERT INTO paesi(paese)VALUES ('Malaysia');
INSERT INTO paesi(paese)VALUES ('Maldive');
INSERT INTO paesi(paese)VALUES ('Mali');
INSERT INTO paesi(paese)VALUES ('Malta');
INSERT INTO paesi(paese)VALUES ('Man, Isola di*');
INSERT INTO paesi(paese)VALUES ('Marocco');
INSERT INTO paesi(paese)VALUES ('Marshall, Isole');
INSERT INTO paesi(paese)VALUES ('Mauritania');
INSERT INTO paesi(paese)VALUES ('Mauritius');
INSERT INTO paesi(paese)VALUES ('Messico');
INSERT INTO paesi(paese)VALUES ('Micronesia, Stati Federati');
INSERT INTO paesi(paese)VALUES ('Moldova');
INSERT INTO paesi(paese)VALUES ('Monaco');
INSERT INTO paesi(paese)VALUES ('Mongolia');
INSERT INTO paesi(paese)VALUES ('Montenegro');
INSERT INTO paesi(paese)VALUES ('Mozambico');
INSERT INTO paesi(paese)VALUES ('Myanmar (ex Birmania)');
INSERT INTO paesi(paese)VALUES ('Namibia');
INSERT INTO paesi(paese)VALUES ('Nauru');
INSERT INTO paesi(paese)VALUES ('Nepal');
INSERT INTO paesi(paese)VALUES ('Nicaragua');
INSERT INTO paesi(paese)VALUES ('Niger');
INSERT INTO paesi(paese)VALUES ('Nigeria');
INSERT INTO paesi(paese)VALUES ('Norvegia');
INSERT INTO paesi(paese)VALUES ('Nuova Zelanda');
INSERT INTO paesi(paese)VALUES ('Oman');
INSERT INTO paesi(paese)VALUES ('Paesi Bassi');
INSERT INTO paesi(paese)VALUES ('Pakistan');
INSERT INTO paesi(paese)VALUES ('Palau');
INSERT INTO paesi(paese)VALUES ('Panama');
INSERT INTO paesi(paese)VALUES ('Papua Nuova Guinea');
INSERT INTO paesi(paese)VALUES ('Paraguay');
INSERT INTO paesi(paese)VALUES ('Perù');
INSERT INTO paesi(paese)VALUES ('Polonia');
INSERT INTO paesi(paese)VALUES ('Portogallo');
INSERT INTO paesi(paese)VALUES ('Qatar');
INSERT INTO paesi(paese)VALUES ('Regno Unito');
INSERT INTO paesi(paese)VALUES ('Repubblica Ceca');
INSERT INTO paesi(paese)VALUES ('Romania');
INSERT INTO paesi(paese)VALUES ('Ruanda');
INSERT INTO paesi(paese)VALUES ('Russa, Federazione');
INSERT INTO paesi(paese)VALUES ('Saint Kitts e Nevis');
INSERT INTO paesi(paese)VALUES ('Saint Lucia');
INSERT INTO paesi(paese)VALUES ('Saint Vincent e Grenadine');
INSERT INTO paesi(paese)VALUES ('Salomone, Isole');
INSERT INTO paesi(paese)VALUES ('Samoa');
INSERT INTO paesi(paese)VALUES ('San Marino');
INSERT INTO paesi(paese)VALUES ('Senegal');
INSERT INTO paesi(paese)VALUES ('Serbia, Repubblica di');
INSERT INTO paesi(paese)VALUES ('Seychelles');
INSERT INTO paesi(paese)VALUES ('Sierra Leone');
INSERT INTO paesi(paese)VALUES ('Singapore');
INSERT INTO paesi(paese)VALUES ('Siria');
INSERT INTO paesi(paese)VALUES ('Slovacchia');
INSERT INTO paesi(paese)VALUES ('Slovenia');
INSERT INTO paesi(paese)VALUES ('Somalia');
INSERT INTO paesi(paese)VALUES ('Spagna');
INSERT INTO paesi(paese)VALUES ('Sri Lanka (ex Ceylon)');
INSERT INTO paesi(paese)VALUES ('Stati Uniti d''America');
INSERT INTO paesi(paese)VALUES ('Stato della Città del Vaticano');
INSERT INTO paesi(paese)VALUES ('Sud Africa');
INSERT INTO paesi(paese)VALUES ('Sud Sudan, Repubblica del');
INSERT INTO paesi(paese)VALUES ('Sudan');
INSERT INTO paesi(paese)VALUES ('Suriname');
INSERT INTO paesi(paese)VALUES ('Svezia');
INSERT INTO paesi(paese)VALUES ('Svizzera');
INSERT INTO paesi(paese)VALUES ('Swaziland');
INSERT INTO paesi(paese)VALUES ('São Tomé e Principe');
INSERT INTO paesi(paese)VALUES ('Tagikistan');
INSERT INTO paesi(paese)VALUES ('Taiwan (ex Formosa)');
INSERT INTO paesi(paese)VALUES ('Tanzania');
INSERT INTO paesi(paese)VALUES ('Territori dell''Autonomia Palestinese');
INSERT INTO paesi(paese)VALUES ('Thailandia');
INSERT INTO paesi(paese)VALUES ('Timor Orientale');
INSERT INTO paesi(paese)VALUES ('Togo');
INSERT INTO paesi(paese)VALUES ('Tonga');
INSERT INTO paesi(paese)VALUES ('Trinidad e Tobago');
INSERT INTO paesi(paese)VALUES ('Tunisia');
INSERT INTO paesi(paese)VALUES ('Turchia');
INSERT INTO paesi(paese)VALUES ('Turkmenistan');
INSERT INTO paesi(paese)VALUES ('Tuvalu');
INSERT INTO paesi(paese)VALUES ('Ucraina');
INSERT INTO paesi(paese)VALUES ('Uganda');
INSERT INTO paesi(paese)VALUES ('Ungheria');
INSERT INTO paesi(paese)VALUES ('Uruguay');
INSERT INTO paesi(paese)VALUES ('Uzbekistan');
INSERT INTO paesi(paese)VALUES ('Vanuatu');
INSERT INTO paesi(paese)VALUES ('Venezuela');
INSERT INTO paesi(paese)VALUES ('Vietnam');
INSERT INTO paesi(paese)VALUES ('Yemen');
INSERT INTO paesi(paese)VALUES ('Zambia');
INSERT INTO paesi(paese)VALUES ('Zimbabwe (ex Rhodesia)');
