INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Poggio, Luca','01-01-1990','1');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hitchcock, Alfred','02-01-1990','2');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sinise, Gary','03-01-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('May, Elaine','04-01-1990','4');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lindberg, Per','05-01-1990','5');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Saks, Gene','06-01-1990','6');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Curtis, Dan','07-01-1990','7');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Barker, Clive','08-01-1990','8');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bergman, Robert','09-01-1990','9');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dante, Joe','10-01-1990','10');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Weill, Claudia','11-01-1990','11');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bernhardt, Curtis','12-01-1990','12');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mankiewicz, Joseph L.','13-01-1990','13');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Berri, Claude','14-01-1990','14');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dahlin, Bob','15-01-1990','15');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kollek, Amos','16-01-1990','16');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Curtiz, Michael','17-01-1990','17');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Daves, Delmer','18-01-1990','18');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Leonard, Robert Z.','19-01-1990','19');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stanley, Paul','20-01-1990','20');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Ray','21-01-1990','21');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Barnard, Michael','22-01-1990','22');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Boulting, Roy','23-01-1990','23');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vidor, Charles','24-01-1990','24');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Silver, Joan Micklin','25-01-1990','25');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Marshall, Penny','26-01-1990','26');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Higgin, Howard','27-01-1990','27');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Glatter, Lesli Linka','28-01-1990','28');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Freed, Mark','29-01-1990','29');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dassin, Jules','30-01-1990','30');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sarafian, Richard C.','31-01-1990','31');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gordon, Steve','01-02-1990','32');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vorhaus, Bernard','02-02-1990','33');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Winkler, Henry','03-02-1990','34');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kloves, Steve','04-02-1990','35');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zucker, David','05-02-1990','36');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Tatoulis, Colin South, John','06-02-1990','37');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Scheerer, Robert','07-02-1990','38');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Myerson, Alan','08-02-1990','39');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mizrahi, Moshe','09-02-1990','40');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Verhoeven, Paul','10-02-1990','41');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ouellette, Jean-Paul','11-02-1990','42');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lawton, J.F.','12-02-1990','43');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Logan, Joshua','13-02-1990','44');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brando, Marlon','14-02-1990','45');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('King, George','15-02-1990','46');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McGann, William','16-02-1990','47');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Olmos, Edward James','17-02-1990','48');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rademakers, Fons','18-02-1990','49');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cronenberg, David','19-02-1990','50');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hopper, Dennis','20-02-1990','51');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Altman, Robert','21-02-1990','52');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Young, Terence','22-02-1990','53');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Truffaut, François','23-02-1990','54');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Axel, Gabriel','24-02-1990','55');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lumet, Sidney','25-02-1990','56');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Winning, David','26-02-1990','57');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Aurel, Jean','27-02-1990','58');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dmytryk, Edward','28-02-1990','59');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Koster, Henry','01-03-1990','60');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bakshi, Ralph','02-03-1990','61');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Drury, David','03-03-1990','62');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Adolphson, Edvin','04-03-1990','63');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Litvak, Anatole','05-03-1990','64');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Molander, Gustaf','06-03-1990','65');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Prior, David A.','07-03-1990','66');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Leigh, Jason','08-03-1990','67');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Eastwood, Clint','09-03-1990','68');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gilliam, Terry','10-03-1990','69');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lee, Spike','11-03-1990','70');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Claxton, William F.','12-03-1990','71');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Allen, Woody','13-03-1990','72');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Auer, John H.','14-03-1990','73');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schnitzer, Robert Allen','15-03-1990','74');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ross, Herbert','16-03-1990','75');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Coolidge, Martha','17-03-1990','76');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kampmann, Steven ','18-03-1990','77');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Young, Robert M.','19-03-1990','78');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Blier, Bertrand','20-03-1990','79');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bill, Tony','21-03-1990','80');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schepisi, Fred','22-03-1990','81');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hoffs, Tamar Simon','23-03-1990','82');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fukasaku, Kinji','24-03-1990','83');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Frank, Melvin','25-03-1990','84');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Amurri, Franco','26-03-1990','85');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bolt, Ben','27-03-1990','86');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hackford, Taylor','28-03-1990','87');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Locke, Sondra','29-03-1990','88');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sagal, Boris','30-03-1990','89');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hughes, John','31-03-1990','90');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lewicki, Steven Jon','01-04-1990','91');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Keach, James','02-04-1990','92');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rudolph, Alan','03-04-1990','93');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Karlson, Phil','04-04-1990','94');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Holland, Savage Steve','05-04-1990','95');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zwick, Edward','06-04-1990','96');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hunt, Peter R.','07-04-1990','97');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Grant, James Edward','08-04-1990','98');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Poitier, Sidney','09-04-1990','99');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('King, Stephen','10-04-1990','100');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Morahan, Christopher','11-04-1990','101');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Streisand, Barbra','12-04-1990','102');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Caton-Jones, Michael','13-04-1990','103');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cannon, Raymond','14-04-1990','104');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dale, Cynthia','15-04-1990','105');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Graef, Roger','16-04-1990','106');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Guest, Val','17-04-1990','107');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kalatozov, Mikhail','18-04-1990','108');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schultz, Michael','19-04-1990','109');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kulik, Buzz','20-04-1990','110');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Konchalovsky, Andrei','21-04-1990','111');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Depardieu, Gérard','22-04-1990','112');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Howson, Frank','23-04-1990','1');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vadim, Roger','24-04-1990','2');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Polanski, Roman','25-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Heckerling, Amy','26-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Meagher, John','27-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('London, Roy','28-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sidaris, Andy','29-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brooks, Richard','30-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mamoulian, Rouben','01-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vidor, King','02-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dragoti, Stan','03-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Winner, Michael','04-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Donaldson, Roger','05-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Loach, Ken','06-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stevens, George','07-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kleiser, Randal','08-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sherman, George','09-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Richardson, Tony','10-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clark, Bob','11-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Edzard, Christine','12-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Howard, Ron','13-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bondarchuk, Sergei','14-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wendkos, Paul','15-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Weeks, Stephen','16-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Griffi, Giuseppe Patroni','17-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Prince, Harold','18-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wimhurst, Jolyon','19-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zemeckis, Robert ','20-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('De Filippo, Eduardo','21-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Neame, Ronald','22-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('August, Bille','23-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Di Leo, Mario','24-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hudson, Hugh','25-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hughes, Terry','26-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mischer, Don','27-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lelouch, Claude','28-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stern, Steven Hilliard','29-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lynch, David','30-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('DeCoteau, David','31-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Godard, Jean-Luc','01-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Burton, Tim','02-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('DeMille, Cecil B.','03-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rosenberg, Stuart','04-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Holzman, Allan','05-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rumar, Craig','06-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Englund, George','07-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Penn, Arthur','08-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Peerce, Larry','09-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('De Sica, Vittorio','10-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Chelsom, Peter','11-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Boleslawski, Richard','12-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mann, Michael','13-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kuzui, Fran Rubel','14-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Chapman, Michael','15-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lafia, John','16-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ramis, Harold','17-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Coen, Joel','18-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('LeRoy, Mervyn','19-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Badham, John','20-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McLaglen, Andrew V.','21-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bradbury, Robert N.','22-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cosmatos, George P.','23-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Smith, Charles Martin','24-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clement, Dick','25-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cimino, Michael','26-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Abrahams, Jim','27-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Corman, Roger','28-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brooks, Albert','29-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Teague, Lewis','30-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dembo, Richard','01-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jones, Chris','02-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Nelson, Gary','03-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Owen, Cliff','04-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Peckinpah, Sam','05-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Smight, Jack','06-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Besson, Luc','07-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Russell, Ken','08-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gilbert, Lewis','09-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Thomas, Ralph','10-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rees, Jerry','11-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pakula, Alan J.','12-07-1990','15');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fleming, Victor','13-07-1990','145');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gibson, Alan','14-07-1990','15');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Green, Guy','15-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Renoir, Jean','16-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Boorman, John','17-07-1990','144');