INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('1', 'SALA 1A', '110', '2', '100');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('2', 'SALA 1B', '110', '3', '100');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('3', 'SALA 1C', '110', '4', '100');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('4', 'SALA 1D', '110', '3', '150');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('5', 'SALA 1E', '110', '3', '150');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('6', 'SALA 2A', '110', '3', '50');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('7', 'SALA 2B', '110', '2', '50');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('8', 'SALA 2C', '110', '2', '50');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('9', 'SALA 2D', '110', '2', '50');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('10','SALA 2E', '110', '2', '100');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('11','SALA 3A', '110', '4', '25');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('12','SALA 3B', '110', '4', '25');
INSERT INTO sale(id_sala, descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('13','SALA 3C', '110', '4', '25');
