INSERT INTO paesi(id_paese, paese)VALUES ('1','Afghanistan');
INSERT INTO paesi(id_paese, paese)VALUES ('2','Albania');
INSERT INTO paesi(id_paese, paese)VALUES ('3','Algeria');
INSERT INTO paesi(id_paese, paese)VALUES ('4','Andorra');
INSERT INTO paesi(id_paese, paese)VALUES ('5','Angola');
INSERT INTO paesi(id_paese, paese)VALUES ('6','Antigua e Barbuda');
INSERT INTO paesi(id_paese, paese)VALUES ('7','Apolide');
INSERT INTO paesi(id_paese, paese)VALUES ('8','Arabia Saudita');
INSERT INTO paesi(id_paese, paese)VALUES ('9','Argentina');
INSERT INTO paesi(id_paese, paese)VALUES ('10','Armenia');
INSERT INTO paesi(id_paese, paese)VALUES ('11','Australia');
INSERT INTO paesi(id_paese, paese)VALUES ('12','Austria');
INSERT INTO paesi(id_paese, paese)VALUES ('13','Azerbaigian');
INSERT INTO paesi(id_paese, paese)VALUES ('14','Bahamas');
INSERT INTO paesi(id_paese, paese)VALUES ('15','Bahrein');
INSERT INTO paesi(id_paese, paese)VALUES ('16','Bangladesh');
INSERT INTO paesi(id_paese, paese)VALUES ('17','Barbados');
INSERT INTO paesi(id_paese, paese)VALUES ('18','Belgio');
INSERT INTO paesi(id_paese, paese)VALUES ('19','Belize');
INSERT INTO paesi(id_paese, paese)VALUES ('20','Benin (ex Dahomey)');
INSERT INTO paesi(id_paese, paese)VALUES ('21','Bhutan');
INSERT INTO paesi(id_paese, paese)VALUES ('22','Bielorussia');
INSERT INTO paesi(id_paese, paese)VALUES ('23','Bolivia');
INSERT INTO paesi(id_paese, paese)VALUES ('24','Bosnia-Erzegovina');
INSERT INTO paesi(id_paese, paese)VALUES ('25','Botswana');
INSERT INTO paesi(id_paese, paese)VALUES ('26','Brasile');
INSERT INTO paesi(id_paese, paese)VALUES ('27','Brunei');
INSERT INTO paesi(id_paese, paese)VALUES ('28','Bulgaria');
INSERT INTO paesi(id_paese, paese)VALUES ('29','Burkina Faso (ex Alto Volta)');
INSERT INTO paesi(id_paese, paese)VALUES ('30','Burundi');
INSERT INTO paesi(id_paese, paese)VALUES ('31','Cambogia');
INSERT INTO paesi(id_paese, paese)VALUES ('32','Camerun');
INSERT INTO paesi(id_paese, paese)VALUES ('33','Canada');
INSERT INTO paesi(id_paese, paese)VALUES ('34','Capo Verde');
INSERT INTO paesi(id_paese, paese)VALUES ('35','Centrafricana, Repubblica');
INSERT INTO paesi(id_paese, paese)VALUES ('36','Ciad');
INSERT INTO paesi(id_paese, paese)VALUES ('37','Cile');
INSERT INTO paesi(id_paese, paese)VALUES ('38','Cinese, Repubblica Popolare');
INSERT INTO paesi(id_paese, paese)VALUES ('39','Cipro');
INSERT INTO paesi(id_paese, paese)VALUES ('40','Colombia');
INSERT INTO paesi(id_paese, paese)VALUES ('41','Comore');
INSERT INTO paesi(id_paese, paese)VALUES ('42','Congo');
INSERT INTO paesi(id_paese, paese)VALUES ('43','Congo, Repubblica democratica del (ex Zaire)');
INSERT INTO paesi(id_paese, paese)VALUES ('44','Corea, Repubblica (Corea del Sud)');
INSERT INTO paesi(id_paese, paese)VALUES ('45','Corea, Repubblica Popolare Democratica (Corea del Nord)');
INSERT INTO paesi(id_paese, paese)VALUES ('46','Costa Rica');
INSERT INTO paesi(id_paese, paese)VALUES ('47','Costa d''Avorio');
INSERT INTO paesi(id_paese, paese)VALUES ('48','Croazia');
INSERT INTO paesi(id_paese, paese)VALUES ('49','Cuba');
INSERT INTO paesi(id_paese, paese)VALUES ('50','Danimarca');
INSERT INTO paesi(id_paese, paese)VALUES ('51','Dominica');
INSERT INTO paesi(id_paese, paese)VALUES ('52','Dominicana, Repubblica');
INSERT INTO paesi(id_paese, paese)VALUES ('53','Ecuador');
INSERT INTO paesi(id_paese, paese)VALUES ('54','Egitto');
INSERT INTO paesi(id_paese, paese)VALUES ('55','El Salvador');
INSERT INTO paesi(id_paese, paese)VALUES ('56','Emirati Arabi Uniti');
INSERT INTO paesi(id_paese, paese)VALUES ('57','Eritrea');
INSERT INTO paesi(id_paese, paese)VALUES ('58','Estonia');
INSERT INTO paesi(id_paese, paese)VALUES ('59','Etiopia');
INSERT INTO paesi(id_paese, paese)VALUES ('60','Figi');
INSERT INTO paesi(id_paese, paese)VALUES ('61','Filippine');
INSERT INTO paesi(id_paese, paese)VALUES ('62','Finlandia');
INSERT INTO paesi(id_paese, paese)VALUES ('63','Francia');
INSERT INTO paesi(id_paese, paese)VALUES ('64','Gabon');
INSERT INTO paesi(id_paese, paese)VALUES ('65','Gambia');
INSERT INTO paesi(id_paese, paese)VALUES ('66','Georgia');
INSERT INTO paesi(id_paese, paese)VALUES ('67','Germania');
INSERT INTO paesi(id_paese, paese)VALUES ('68','Ghana');
INSERT INTO paesi(id_paese, paese)VALUES ('69','Giamaica');
INSERT INTO paesi(id_paese, paese)VALUES ('70','Giappone');
INSERT INTO paesi(id_paese, paese)VALUES ('71','Gibuti');
INSERT INTO paesi(id_paese, paese)VALUES ('72','Giordania');
INSERT INTO paesi(id_paese, paese)VALUES ('73','Grecia');
INSERT INTO paesi(id_paese, paese)VALUES ('74','Grenada');
INSERT INTO paesi(id_paese, paese)VALUES ('75','Guatemala');
INSERT INTO paesi(id_paese, paese)VALUES ('76','Guinea');
INSERT INTO paesi(id_paese, paese)VALUES ('77','Guinea Bissau');
INSERT INTO paesi(id_paese, paese)VALUES ('78','Guinea Equatoriale');
INSERT INTO paesi(id_paese, paese)VALUES ('79','Guyana');
INSERT INTO paesi(id_paese, paese)VALUES ('80','Haiti');
INSERT INTO paesi(id_paese, paese)VALUES ('81','Honduras');
INSERT INTO paesi(id_paese, paese)VALUES ('82','India');
INSERT INTO paesi(id_paese, paese)VALUES ('83','Indonesia');
INSERT INTO paesi(id_paese, paese)VALUES ('84','Iran, Repubblica Islamica del');
INSERT INTO paesi(id_paese, paese)VALUES ('85','Iraq');
INSERT INTO paesi(id_paese, paese)VALUES ('86','Irlanda');
INSERT INTO paesi(id_paese, paese)VALUES ('87','Islanda');
INSERT INTO paesi(id_paese, paese)VALUES ('88','Israele');
INSERT INTO paesi(id_paese, paese)VALUES ('89','Jersey, Isole*');
INSERT INTO paesi(id_paese, paese)VALUES ('90','Kazakhstan');
INSERT INTO paesi(id_paese, paese)VALUES ('91','Kenya');
INSERT INTO paesi(id_paese, paese)VALUES ('92','Kirghizistan');
INSERT INTO paesi(id_paese, paese)VALUES ('93','Kiribati');
INSERT INTO paesi(id_paese, paese)VALUES ('94','Kosovo');
INSERT INTO paesi(id_paese, paese)VALUES ('95','Kuwait');
INSERT INTO paesi(id_paese, paese)VALUES ('96','Laos');
INSERT INTO paesi(id_paese, paese)VALUES ('97','Lesotho');
INSERT INTO paesi(id_paese, paese)VALUES ('98','Lettonia');
INSERT INTO paesi(id_paese, paese)VALUES ('99','Libano');
INSERT INTO paesi(id_paese, paese)VALUES ('100','Liberia');
INSERT INTO paesi(id_paese, paese)VALUES ('101','Libia');
INSERT INTO paesi(id_paese, paese)VALUES ('102','Liechtenstein');
INSERT INTO paesi(id_paese, paese)VALUES ('103','Lituania');
INSERT INTO paesi(id_paese, paese)VALUES ('104','Lussemburgo');
INSERT INTO paesi(id_paese, paese)VALUES ('105','Macedonia, Repubblica di');
INSERT INTO paesi(id_paese, paese)VALUES ('106','Madagascar');
INSERT INTO paesi(id_paese, paese)VALUES ('107','Malawi');
INSERT INTO paesi(id_paese, paese)VALUES ('108','Malaysia');
INSERT INTO paesi(id_paese, paese)VALUES ('109','Maldive');
INSERT INTO paesi(id_paese, paese)VALUES ('110','Mali');
INSERT INTO paesi(id_paese, paese)VALUES ('111','Malta');
INSERT INTO paesi(id_paese, paese)VALUES ('112','Man, Isola di*');
INSERT INTO paesi(id_paese, paese)VALUES ('113','Marocco');
INSERT INTO paesi(id_paese, paese)VALUES ('114','Marshall, Isole');
INSERT INTO paesi(id_paese, paese)VALUES ('115','Mauritania');
INSERT INTO paesi(id_paese, paese)VALUES ('116','Mauritius');
INSERT INTO paesi(id_paese, paese)VALUES ('117','Messico');
INSERT INTO paesi(id_paese, paese)VALUES ('118','Micronesia, Stati Federati');
INSERT INTO paesi(id_paese, paese)VALUES ('119','Moldova');
INSERT INTO paesi(id_paese, paese)VALUES ('120','Monaco');
INSERT INTO paesi(id_paese, paese)VALUES ('121','Mongolia');
INSERT INTO paesi(id_paese, paese)VALUES ('122','Montenegro');
INSERT INTO paesi(id_paese, paese)VALUES ('123','Mozambico');
INSERT INTO paesi(id_paese, paese)VALUES ('124','Myanmar (ex Birmania)');
INSERT INTO paesi(id_paese, paese)VALUES ('125','Namibia');
INSERT INTO paesi(id_paese, paese)VALUES ('126','Nauru');
INSERT INTO paesi(id_paese, paese)VALUES ('127','Nepal');
INSERT INTO paesi(id_paese, paese)VALUES ('128','Nicaragua');
INSERT INTO paesi(id_paese, paese)VALUES ('129','Niger');
INSERT INTO paesi(id_paese, paese)VALUES ('130','Nigeria');
INSERT INTO paesi(id_paese, paese)VALUES ('131','Norvegia');
INSERT INTO paesi(id_paese, paese)VALUES ('132','Nuova Zelanda');
INSERT INTO paesi(id_paese, paese)VALUES ('133','Oman');
INSERT INTO paesi(id_paese, paese)VALUES ('134','Paesi Bassi');
INSERT INTO paesi(id_paese, paese)VALUES ('135','Pakistan');
INSERT INTO paesi(id_paese, paese)VALUES ('136','Palau');
INSERT INTO paesi(id_paese, paese)VALUES ('137','Panama');
INSERT INTO paesi(id_paese, paese)VALUES ('138','Papua Nuova Guinea');
INSERT INTO paesi(id_paese, paese)VALUES ('139','Paraguay');
INSERT INTO paesi(id_paese, paese)VALUES ('140','Perù');
INSERT INTO paesi(id_paese, paese)VALUES ('141','Polonia');
INSERT INTO paesi(id_paese, paese)VALUES ('142','Portogallo');
INSERT INTO paesi(id_paese, paese)VALUES ('143','Qatar');
INSERT INTO paesi(id_paese, paese)VALUES ('144','Regno Unito');
INSERT INTO paesi(id_paese, paese)VALUES ('145','Repubblica Ceca');
INSERT INTO paesi(id_paese, paese)VALUES ('146','Romania');
INSERT INTO paesi(id_paese, paese)VALUES ('147','Ruanda');
INSERT INTO paesi(id_paese, paese)VALUES ('148','Russa, Federazione');
INSERT INTO paesi(id_paese, paese)VALUES ('149','Saint Kitts e Nevis');
INSERT INTO paesi(id_paese, paese)VALUES ('150','Saint Lucia');
INSERT INTO paesi(id_paese, paese)VALUES ('151','Saint Vincent e Grenadine');
INSERT INTO paesi(id_paese, paese)VALUES ('152','Salomone, Isole');
INSERT INTO paesi(id_paese, paese)VALUES ('153','Samoa');
INSERT INTO paesi(id_paese, paese)VALUES ('154','San Marino');
INSERT INTO paesi(id_paese, paese)VALUES ('155','Senegal');
INSERT INTO paesi(id_paese, paese)VALUES ('156','Serbia, Repubblica di');
INSERT INTO paesi(id_paese, paese)VALUES ('157','Seychelles');
INSERT INTO paesi(id_paese, paese)VALUES ('158','Sierra Leone');
INSERT INTO paesi(id_paese, paese)VALUES ('159','Singapore');
INSERT INTO paesi(id_paese, paese)VALUES ('160','Siria');
INSERT INTO paesi(id_paese, paese)VALUES ('161','Slovacchia');
INSERT INTO paesi(id_paese, paese)VALUES ('162','Slovenia');
INSERT INTO paesi(id_paese, paese)VALUES ('163','Somalia');
INSERT INTO paesi(id_paese, paese)VALUES ('164','Spagna');
INSERT INTO paesi(id_paese, paese)VALUES ('165','Sri Lanka (ex Ceylon)');
INSERT INTO paesi(id_paese, paese)VALUES ('166','Stati Uniti d''America');
INSERT INTO paesi(id_paese, paese)VALUES ('167','Stato della Città del Vaticano');
INSERT INTO paesi(id_paese, paese)VALUES ('168','Sud Africa');
INSERT INTO paesi(id_paese, paese)VALUES ('169','Sud Sudan, Repubblica del');
INSERT INTO paesi(id_paese, paese)VALUES ('170','Sudan');
INSERT INTO paesi(id_paese, paese)VALUES ('171','Suriname');
INSERT INTO paesi(id_paese, paese)VALUES ('172','Svezia');
INSERT INTO paesi(id_paese, paese)VALUES ('173','Svizzera');
INSERT INTO paesi(id_paese, paese)VALUES ('174','Swaziland');
INSERT INTO paesi(id_paese, paese)VALUES ('175','São Tomé e Principe');
INSERT INTO paesi(id_paese, paese)VALUES ('176','Tagikistan');
INSERT INTO paesi(id_paese, paese)VALUES ('177','Taiwan (ex Formosa)');
INSERT INTO paesi(id_paese, paese)VALUES ('178','Tanzania');
INSERT INTO paesi(id_paese, paese)VALUES ('179','Territori dell''Autonomia Palestinese');
INSERT INTO paesi(id_paese, paese)VALUES ('180','Thailandia');
INSERT INTO paesi(id_paese, paese)VALUES ('181','Timor Orientale');
INSERT INTO paesi(id_paese, paese)VALUES ('182','Togo');
INSERT INTO paesi(id_paese, paese)VALUES ('183','Tonga');
INSERT INTO paesi(id_paese, paese)VALUES ('184','Trinidad e Tobago');
INSERT INTO paesi(id_paese, paese)VALUES ('185','Tunisia');
INSERT INTO paesi(id_paese, paese)VALUES ('186','Turchia');
INSERT INTO paesi(id_paese, paese)VALUES ('187','Turkmenistan');
INSERT INTO paesi(id_paese, paese)VALUES ('188','Tuvalu');
INSERT INTO paesi(id_paese, paese)VALUES ('189','Ucraina');
INSERT INTO paesi(id_paese, paese)VALUES ('190','Uganda');
INSERT INTO paesi(id_paese, paese)VALUES ('191','Ungheria');
INSERT INTO paesi(id_paese, paese)VALUES ('192','Uruguay');
INSERT INTO paesi(id_paese, paese)VALUES ('193','Uzbekistan');
INSERT INTO paesi(id_paese, paese)VALUES ('194','Vanuatu');
INSERT INTO paesi(id_paese, paese)VALUES ('195','Venezuela');
INSERT INTO paesi(id_paese, paese)VALUES ('196','Vietnam');
INSERT INTO paesi(id_paese, paese)VALUES ('197','Yemen');
INSERT INTO paesi(id_paese, paese)VALUES ('198','Zambia');
INSERT INTO paesi(id_paese, paese)VALUES ('199','Zimbabwe (ex Rhodesia)');