INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Look Who''s Talking','1989','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Driving Miss Daisy','1989','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Turner & Hooch','1989','1','65','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Born on the Fourth of July','1989','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Field of Dreams','1989','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Uncle Buck','1989','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('When Harry Met Sally...','1989','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dead Poets Society','1989','1','75','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Parenthood','1989','1','75','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lethal Weapon 2','1989','1','75','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The War of the Roses','1989','1','75','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('National Lampoon''s Christmas Vacation','1989','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Honey I Shrunk the Kids','1989','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman','1989','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ghostbusters II','1989','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Little Mermaid','1989','1','83','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Back to the Future Part II','1989','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Indiana Jones and the Last Crusade','1989','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tango & Cash','1989','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Steel Magnolias','1989','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Three Men and a Little Lady','1990','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Teenage Mutant Ninja Turtles','1990','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pretty Woman','1990','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Kindergarten Cop','1990','1','111','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Home Alone','1990','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bird on a Wire','1990','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Misery','1990','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Edward Scissorhands','1990','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ghost','1990','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Presumed Innocent','1990','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dances with Wolves','1990','1','181','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Flatliners','1990','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hunt for Red October','1990','1','134','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Another 48 Hrs.','1990','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Back to the Future Part III','1990','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dick Tracy','1990','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Godfather: Part III','1990','1','162','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Days of Thunder','1990','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Total Recall','1990','1','113','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Die Hard 2','1990','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fried Green Tomatoes','1991','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Silence of the Lambs','1991','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sleeping with the Enemy','1991','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Father of the Bride','1991','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Naked Gun 2 1/2: The Smell of Fear','1991','1','85','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Teenage Mutant Ninja Turtles II','1991','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Beauty and the Beast','1991','1','84','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hot Shots!','1991','1','84','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('City Slickers','1991','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek VI: The Undiscovered Country','1991','1','113','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Addams Family','1991','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Prince of Tides','1991','1','132','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('What About Bob?','1991','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cape Fear','1991','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('JFK','1991','1','189','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Robin Hood: Prince of Thieves','1991','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hook','1991','1','144','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Backdraft','1991','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Terminator 2: Judgment Day','1991','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Crying Game','1992','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hand that Rocks the Cradle','1992','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Unforgiven','1992','1','131','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Home Alone 2: Lost in New York','1992','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wayne''s World','1992','1','94','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Bodyguard','1992','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Aladdin','1992','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('White Men Can''t Jump','1992','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sister Act','1992','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scent of a Woman','1992','1','157','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lethal Weapon 3','1992','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Under Siege','1992','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Boomerang','1992','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A League of Their Own','1992','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Last of the Mohicans','1992','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bram Stoker''s Dracula','1992','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Few Good Men','1992','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Patriot Games','1992','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Basic Instinct','1992','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman Returns','1992','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cool Runnings','1993','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Groundhog Day','1993','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Free Willy','1993','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sleepless in Seattle','1993','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Schindler''s List','1993','1','195','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mrs. Doubtfire','1993','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tombstone','1993','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Philadelphia','1993','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dave','1993','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Grumpy Old Men','1993','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Indecent Proposal','1993','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sister Act 2: Back in the Habit','1993','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('In the Line of Fire','1993','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rising Sun','1993','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Firm','1993','1','154','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Fugitive','1993','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Pelican Brief','1993','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Demolition Man','1993','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cliffhanger','1993','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jurassic Park III','2001','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pulp Fiction','1994','1','154','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ace Ventura: Pet Detective','1994','1','86','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dumb and Dumber','1994','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Santa Clause','1994','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Mask','1994','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Speed','1994','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Legends of the Fall','1994','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek: Generations','1994','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lion King','1994','1','89','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Client','1994','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Specialist','1994','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Flintstones','1994','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Forrest Gump','1994','1','142','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Stargate','1994','1','121','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Disclosure','1994','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Interview with the Vampire','1994','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Clear and Present Danger','1994','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wolf','1994','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Maverick','1994','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('True Lies','1994','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('While You Were Sleeping','1995','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dangerous Minds','1995','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Grumpier Old Men','1995','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Father of the Bride Part II','1995','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Toy Story','1995','1','81','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ace Ventura: When Nature Calls','1995','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Get Shorty','1995','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mr. Holland''s Opus','1995','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Se7en','1995','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Casper','1995','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Congo','1995','1','109','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Apollo 13','1995','1','140','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Crimson Tide','1995','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pocahontas','1995','1','81','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('GoldenEye','1995','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jumanji','1995','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Braveheart','1995','1','177','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Die Hard: With a Vengeance','1995','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman Forever','1995','1','121','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Waterworld','1995','1','135','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scream','1996','1','111','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The First Wives Club','1996','1','102','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The English Patient','1996','1','162','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Birdcage','1996','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Phenomenon','1996','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Time to Kill','1996','1','149','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek: First Contact','1996','1','111','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Broken Arrow','1996','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jerry Maguire','1996','1','139','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Nutty Professor','1996','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('101 Dalmatians','1996','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Rock','1996','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Independence Day','1996','1','145','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mission: Impossible','1996','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ransom','1996','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Space Jam','1996','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Twister','1996','1','113','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hunchback of Notre Dame','1996','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Eraser','1996','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Michael','1996','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Good Will Hunting','1997','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('I Know What You Did Last Summer','1997','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scream 2','1997','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('My Best Friend''s Wedding','1997','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Liar Liar','1997','1','86','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('As Good as It Gets','1997','1','139','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('George of the Jungle','1997','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lost World: Jurassic Park','1997','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Con Air','1997','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Conspiracy Theory','1997','1','135','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Face/Off','1997','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Flubber','1997','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hercules','1997','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Air Force One','1997','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Men in Black','1997','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Contact','1997','1','150','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tomorrow Never Dies','1997','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman and Robin','1997','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Titanic','1997','1','194','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('There''s Something About Mary','1998','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Waterboy','1998','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shakespeare in Love','1998','1','122','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Rugrats Movie','1998','1','79','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rush Hour','1998','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Stepmom','1998','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Patch Adams','1998','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Truman Show','1998','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('You''ve Got Mail','1998','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Saving Private Ryan','1998','1','169','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Prince of Egypt','1998','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Doctor Dolittle','1998','1','85','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Deep Impact','1998','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mulan','1998','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Enemy of the State','1998','1','132','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Mask of Zorro','1998','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Bug''s Life','1998','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Godzilla','1998','1','139','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Armageddon','1998','1','151','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lethal Weapon 4','1998','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Blair Witch Project','1999','1','81','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('American Pie','1999','1','95','');


