INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Poggio, Luca','01-01-1990','1');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hitchcock, Alfred','02-01-1990','2');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sinise, Gary','03-01-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('May, Elaine','04-01-1990','4');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lindberg, Per','05-01-1990','5');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Saks, Gene','06-01-1990','6');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Curtis, Dan','07-01-1990','7');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Barker, Clive','08-01-1990','8');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bergman, Robert','09-01-1990','9');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dante, Joe','10-01-1990','10');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Weill, Claudia','11-01-1990','11');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bernhardt, Curtis','12-01-1990','12');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mankiewicz, Joseph L.','13-01-1990','13');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Berri, Claude','14-01-1990','14');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dahlin, Bob','15-01-1990','15');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kollek, Amos','16-01-1990','16');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Curtiz, Michael','17-01-1990','17');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Daves, Delmer','18-01-1990','18');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Leonard, Robert Z.','19-01-1990','19');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stanley, Paul','20-01-1990','20');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Ray','21-01-1990','21');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Barnard, Michael','22-01-1990','22');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Boulting, Roy','23-01-1990','23');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vidor, Charles','24-01-1990','24');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Silver, Joan Micklin','25-01-1990','25');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Marshall, Penny','26-01-1990','26');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Higgin, Howard','27-01-1990','27');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Glatter, Lesli Linka','28-01-1990','28');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Freed, Mark','29-01-1990','29');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dassin, Jules','30-01-1990','30');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sarafian, Richard C.','31-01-1990','31');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gordon, Steve','01-02-1990','32');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vorhaus, Bernard','02-02-1990','33');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Winkler, Henry','03-02-1990','34');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kloves, Steve','04-02-1990','35');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zucker, David','05-02-1990','36');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Tatoulis, Colin South, John','06-02-1990','37');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Scheerer, Robert','07-02-1990','38');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Myerson, Alan','08-02-1990','39');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mizrahi, Moshe','09-02-1990','40');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Verhoeven, Paul','10-02-1990','41');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ouellette, Jean-Paul','11-02-1990','42');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lawton, J.F.','12-02-1990','43');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Logan, Joshua','13-02-1990','44');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brando, Marlon','14-02-1990','45');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('King, George','15-02-1990','46');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McGann, William','16-02-1990','47');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Olmos, Edward James','17-02-1990','48');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rademakers, Fons','18-02-1990','49');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cronenberg, David','19-02-1990','50');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hopper, Dennis','20-02-1990','51');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Altman, Robert','21-02-1990','52');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Young, Terence','22-02-1990','53');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Truffaut, François','23-02-1990','54');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Axel, Gabriel','24-02-1990','55');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lumet, Sidney','25-02-1990','56');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Winning, David','26-02-1990','57');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Aurel, Jean','27-02-1990','58');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dmytryk, Edward','28-02-1990','59');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Koster, Henry','01-03-1990','60');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bakshi, Ralph','02-03-1990','61');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Drury, David','03-03-1990','62');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Adolphson, Edvin','04-03-1990','63');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Litvak, Anatole','05-03-1990','64');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Molander, Gustaf','06-03-1990','65');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Prior, David A.','07-03-1990','66');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Leigh, Jason','08-03-1990','67');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Eastwood, Clint','09-03-1990','68');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gilliam, Terry','10-03-1990','69');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lee, Spike','11-03-1990','70');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Claxton, William F.','12-03-1990','71');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Allen, Woody','13-03-1990','72');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Auer, John H.','14-03-1990','73');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schnitzer, Robert Allen','15-03-1990','74');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ross, Herbert','16-03-1990','75');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Coolidge, Martha','17-03-1990','76');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kampmann, Steven ','18-03-1990','77');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Young, Robert M.','19-03-1990','78');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Blier, Bertrand','20-03-1990','79');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bill, Tony','21-03-1990','80');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schepisi, Fred','22-03-1990','81');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hoffs, Tamar Simon','23-03-1990','82');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fukasaku, Kinji','24-03-1990','83');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Frank, Melvin','25-03-1990','84');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Amurri, Franco','26-03-1990','85');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bolt, Ben','27-03-1990','86');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hackford, Taylor','28-03-1990','87');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Locke, Sondra','29-03-1990','88');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sagal, Boris','30-03-1990','89');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hughes, John','31-03-1990','90');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lewicki, Steven Jon','01-04-1990','91');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Keach, James','02-04-1990','92');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rudolph, Alan','03-04-1990','93');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Karlson, Phil','04-04-1990','94');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Holland, Savage Steve','05-04-1990','95');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zwick, Edward','06-04-1990','96');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hunt, Peter R.','07-04-1990','97');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Grant, James Edward','08-04-1990','98');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Poitier, Sidney','09-04-1990','99');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('King, Stephen','10-04-1990','100');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Morahan, Christopher','11-04-1990','101');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Streisand, Barbra','12-04-1990','102');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Caton-Jones, Michael','13-04-1990','103');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cannon, Raymond','14-04-1990','104');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dale, Cynthia','15-04-1990','105');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Graef, Roger','16-04-1990','106');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Guest, Val','17-04-1990','107');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kalatozov, Mikhail','18-04-1990','108');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schultz, Michael','19-04-1990','109');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kulik, Buzz','20-04-1990','110');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Konchalovsky, Andrei','21-04-1990','111');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Depardieu, Gérard','22-04-1990','112');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Howson, Frank','23-04-1990','1');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vadim, Roger','24-04-1990','2');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Polanski, Roman','25-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Heckerling, Amy','26-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Meagher, John','27-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('London, Roy','28-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sidaris, Andy','29-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brooks, Richard','30-04-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mamoulian, Rouben','01-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vidor, King','02-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dragoti, Stan','03-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Winner, Michael','04-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Donaldson, Roger','05-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Loach, Ken','06-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stevens, George','07-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kleiser, Randal','08-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sherman, George','09-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Richardson, Tony','10-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clark, Bob','11-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Edzard, Christine','12-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Howard, Ron','13-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bondarchuk, Sergei','14-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wendkos, Paul','15-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Weeks, Stephen','16-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Griffi, Giuseppe Patroni','17-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Prince, Harold','18-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wimhurst, Jolyon','19-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zemeckis, Robert ','20-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('De Filippo, Eduardo','21-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Neame, Ronald','22-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('August, Bille','23-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Di Leo, Mario','24-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hudson, Hugh','25-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hughes, Terry','26-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mischer, Don','27-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lelouch, Claude','28-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stern, Steven Hilliard','29-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lynch, David','30-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('DeCoteau, David','31-05-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Godard, Jean-Luc','01-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Burton, Tim','02-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('DeMille, Cecil B.','03-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rosenberg, Stuart','04-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Holzman, Allan','05-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rumar, Craig','06-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Englund, George','07-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Penn, Arthur','08-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Peerce, Larry','09-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('De Sica, Vittorio','10-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Chelsom, Peter','11-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Boleslawski, Richard','12-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mann, Michael','13-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kuzui, Fran Rubel','14-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Chapman, Michael','15-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lafia, John','16-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ramis, Harold','17-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Coen, Joel','18-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('LeRoy, Mervyn','19-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Badham, John','20-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McLaglen, Andrew V.','21-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bradbury, Robert N.','22-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cosmatos, George P.','23-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Smith, Charles Martin','24-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clement, Dick','25-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cimino, Michael','26-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Abrahams, Jim','27-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Corman, Roger','28-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brooks, Albert','29-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Teague, Lewis','30-06-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dembo, Richard','01-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jones, Chris','02-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Nelson, Gary','03-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Owen, Cliff','04-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Peckinpah, Sam','05-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Smight, Jack','06-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Besson, Luc','07-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Russell, Ken','08-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gilbert, Lewis','09-07-1990','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Thomas, Ralph','10-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rees, Jerry','11-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pakula, Alan J.','12-07-1990','15');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fleming, Victor','13-07-1990','145');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gibson, Alan','14-07-1990','15');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Green, Guy','15-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Renoir, Jean','16-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Boorman, John','17-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wicki, Bernhard','18-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Anger, Kenneth','19-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Walsh, Raoul','20-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Furie, Sidney J.','21-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Beineix, Jean-Jacques','22-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Castle, Nick','23-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Widerberg, Bo','24-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Chouraqui, Elie','25-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Quinn, James','26-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Parrish, Robert','27-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stevenson, Robert','28-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hobbs, Lyndall','29-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brown, Clarence','30-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fitzmaurice, George','31-07-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Niblo, Fred','01-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cameron, James','02-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Guillermin, John','03-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Oz, Frank','04-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ritchie, Michael','05-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Holcomb, Rod','06-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zinnemann, Fred','07-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Emes, Ian','08-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Waris, Hussein','09-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Scott, Tony','10-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stockwell, John','11-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wertmuller, Lina','12-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Soderbergh, Steven','13-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brooks, James L.','14-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dinner, Michael','15-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Barbash, Uri','16-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Greenaway, Peter','17-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Negulesco, Jean','18-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('DeVito, Danny','19-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Baz','20-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Morneau, Louis','21-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Patrick, John','22-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Manning, Michelle','23-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ruggles, Wesley','24-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Petrie, Donald','25-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Couturie, Bill','26-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Battersby, Roy','27-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ford, Philip','28-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Harrington, Curtis','29-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lester, Mark L.','30-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Penn, Leo','31-08-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pontecorvo, Gillo','01-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Robinson, John Mark','02-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stevens, George, Jr.','03-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Loma, José Antonio de la','04-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sebastian, Beverly','05-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Milius, John','06-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Young, Terrence','07-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Donaggio, Michael Winner','08-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Romero, George A.','09-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bourguignon, Serge','10-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lambert, Mary','11-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Reiner, Rob','12-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kaufman, Philip','13-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ruben, Joseph','14-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ray, Nicholas','15-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kurosawa, Akira','16-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Comeau, Alain','17-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kramer, Stanley','18-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Needham, Hal','19-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Golden, Dan','20-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hickox, Douglas','21-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mulligan, Robert','22-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wilson, Hugh','23-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jordan, Neil','24-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Beatty, Warren','25-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Neff, Thomas L.','26-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Avildsen, John G.','27-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Blot, Philippe','28-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cohen, Martin B.','29-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hook, Harry','30-09-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hanson, Curtis','01-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McGrath, Joseph','02-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Costner, Kevin','03-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sherman, Gary','04-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sayles, John','05-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Figgis, Mike','06-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brooks, Mel','07-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('O''Herlihy, Michael','08-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cook, Fielder','09-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Phillips, Maurice','10-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Haines, Fred','11-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hunter, Tim','12-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Grosbard, Ulu','13-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cromwell, John','14-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Apted, Michael','15-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kaurismäki, Mika','16-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vigne, Daniel','17-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Walters, Charles','18-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Serious, Yahoo','19-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Newman, Paul','20-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gower, Bruce','21-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kellogg, Ray','22-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kennedy, Burt','23-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Quisenberry, Byron','24-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sanger, Jonathan','25-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sevush, Herb','26-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Siodmak, Robert','27-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stiller, Mauritz','28-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Tourneur, Jacques','29-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Nuytten, Bruno','30-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Spielberg, Steven','31-10-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Thompson, J. Lee','01-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hill, George Roy','02-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Alda, Alan','03-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Thorpe, Richard','04-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bradley, Al','05-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ford, Greg','06-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Nichols, Mike','07-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Donen, Stanley','08-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Joffe, Roland','09-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Feferman, Linda','10-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Corneau, Alan','11-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sturges, John','12-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lisberger, Steven','13-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stone, Oliver','14-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rossen, Robert','15-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hyam, Peter','16-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sandrich, Jay','17-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Post, Ted','18-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lattuada, Alberto','19-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schatzberg, Jerry','20-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Marder, Bruce','21-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Costa-Gavras','22-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Patterson, Willi','23-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Totten, Robert','24-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Preminger, Otto','25-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Travis, Mark W.','26-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Antonioni, Michelangelo','27-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wilcox, Fred M','28-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fleischer, Richard','29-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Yorkin, Bud','30-11-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Arnold, Newt','01-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Aslanian, Samson','02-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clegg, Tom','03-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Degas, Andre','04-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Irvin, John','05-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sholder, Jack','06-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Puenzo, Luiz','07-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Huston, John','08-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Edwards, Blake','09-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Frears, Stephen','10-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schaffner, Franklin J.','11-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Benton, Robert','12-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Jud','13-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Winkler, Irwin','14-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Forman, Milos','15-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Varda, Agnes','16-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Babenco, Hector','17-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bahr, Fax','18-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wright, Thomas J.','19-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hyams, Peter','20-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Tuchner, Michael','21-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Resnais, Alain','22-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Carpenter, John','23-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Conway, Jack','24-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sherman, Vincent','25-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dickerson, Ernest R.','26-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kaczender, George','27-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hallström, Lasse','28-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Barreto, Bruno','29-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Barry, Michael','30-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mann, Anthony','31-12-1990','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gibbins, Duncan','01-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Parker, Alan','02-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Benjamin, Richard','03-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schumacher, Joel','04-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Quinn, John','05-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bogart, Paul','06-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zeffirelli, Franco','07-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hutton, Brian G.','08-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Savoca, Nancy','09-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Matthau, Charles','10-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Guney, Yilmaz','11-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Petrie, Daniel','12-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Strock, Herbert L.','13-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Thomas, Gerald','14-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bertolucci, Bernardo','15-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ford, John','16-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pillsbury, Sam','17-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Vanwagenen, Sterling','18-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Crosland, Alan','19-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Philips, Lee','20-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rossellini, Roberto','21-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Crichton, Michael','22-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('King Keller, Frederick','23-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Day, Robert','24-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gries, Tom','25-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jewison, Norman','26-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lathan, Stan','27-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ashby, Hal','28-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Sam','29-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Siegel, Don','30-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schmoeller, David','31-01-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brickman, Paul','01-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Garnett, Tay','02-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kubrick, Stanley','03-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dwan, Allan','04-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bridges, James','05-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ruben, Katt Shea','06-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Franklin, Sidney','07-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brand, Larry','08-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Oliansky, Joel','09-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Nimoy, Leonard','10-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mann, Delbert','11-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brickman, Marshall','12-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Arkush, Allan','13-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Aykroyd, Dan','14-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bowser, Kenneth','15-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Shatner, William ','16-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Reis, Irving','17-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Forbes, Bryan','18-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fisher, Jack','19-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rossi, Franco','20-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Silver, Marisa','21-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sharman, Jim','22-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Trikonis, Gus','23-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ward, David S.','24-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bogner, Willy','25-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Menzel, Jiri','26-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Murphy, Eddie','27-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Newell, Mike','28-02-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('O''Connor, Pat','01-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Reed, Jerry','02-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wajda, Andrzej','03-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Coppola, Francis Ford','04-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hopkins, Stephen','05-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Attenborough, Richard','06-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lyne, Adrian','07-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McCarey, Leo','08-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Seaton, George','09-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Nelson, Ralph','10-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fellini, Federico','11-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Don','12-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ritt, Martin','13-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schroeder, Barbet','14-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Brest, Martin','15-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Troell, Jan','16-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Avnet, John','17-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Chomsky, Marvin J.','18-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lederman, Ross','19-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Smithey, Alan','20-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sonnenfeld, B.','21-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jaglom, Henry','22-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sternberg, Josef von','23-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Amateau, Rod','24-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rayfield, David','25-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Scola, Ettore','26-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('De Winter, Harry','27-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Martino, Sergio','28-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Haines, Randa','29-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kotcheff, Ted','30-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lean, David','31-03-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Benedek, Laslo','01-04-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Birch, Patricia','02-04-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stern, Sandor','03-04-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schrader, Paul','04-04-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clayton, Jack','05-04-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zemeckis, Robert','06-04-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Miles, Christopher','07-04-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fanaka, Jamaa','08-04-1991','144');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lloyd, Frank','09-04-1991','1');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McEveety, Vincent','10-04-1991','2');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stuart, Mel','11-04-1991','3');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taurog, Norman','12-04-1991','4');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lester, Richard','13-04-1991','5');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cicatiello, Lucio','14-04-1991','6');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hughes, Ken','15-04-1991','7');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wise, Robert','16-04-1991','8');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kagan, Jeremy Paul','17-04-1991','9');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Scorsese, Martin','18-04-1991','10');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jones, David','19-04-1991','11');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Allegret, Marc','20-04-1991','12');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Boisrond, Michel','21-04-1991','13');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Molander, Gustav','22-04-1991','14');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sargent, Joseph','23-04-1991','15');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schlesinger, John','24-04-1991','16');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Anthony, Joseph','25-04-1991','17');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Duigan, John','26-04-1991','18');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Walton, Kip','27-04-1991','19');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wyler, William','28-04-1991','20');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jameson, Jerry','29-04-1991','21');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mulcahy, Russell','30-04-1991','22');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Higgins, Colin','01-05-1991','23');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lang, Walter','02-05-1991','24');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Thompson, Brett','03-05-1991','25');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wiemer, Robert','04-05-1991','26');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Damski, Mel','05-05-1991','27');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('King, Rick','06-05-1991','28');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Byrne, David','07-05-1991','29');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Finch, Charles','08-05-1991','30');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Van Peebles, Mario','09-05-1991','31');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pal, George','10-05-1991','32');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fosse, Bob','11-05-1991','33');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Dan','12-05-1991','34');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Colla, Richard A.','13-05-1991','35');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Deutch, Howard','14-05-1991','36');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Reisz, Karel','15-05-1991','37');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Flicker, Theodore J.','16-05-1991','38');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wilder, Billy','17-05-1991','39');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hellman, Oliver','18-05-1991','40');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Madsen, Kenneth','19-05-1991','41');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Leone, Sergio','20-05-1991','42');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Chaplin, Charles','21-05-1991','43');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Douglas, Kirk','22-05-1991','44');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ludman, Larry','23-05-1991','45');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Miller, David','24-05-1991','46');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Nicholson, Arch','25-05-1991','47');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Donner, Richard','26-05-1991','48');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Noyce, Phillip','27-05-1991','49');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Heston, Charlton','28-05-1991','50');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pearce, Richard','29-05-1991','51');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cukor, George','30-05-1991','52');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hamilton, Guy','31-05-1991','53');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mackenzie, John','01-06-1991','54');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gottlieb, Michael','02-06-1991','55');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Miller, George','03-06-1991','56');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Szabó, István','04-06-1991','57');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hathaway, Henry','05-06-1991','58');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hermoso, Miguel','06-06-1991','59');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Band, Charles','07-06-1991','60');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Belson, Jerry','08-06-1991','61');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Silverstein, Elliot','09-06-1991','62');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Foley, James','10-06-1991','63');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Miller, Robert Ellis','11-06-1991','64');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Florea, John','12-06-1991','65');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Miller, Stuart','13-06-1991','66');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Anspaugh, David','14-06-1991','67');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Levy, Ralph','15-06-1991','68');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wilder, Gene','16-06-1991','69');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Colmes, Walter','17-06-1991','70');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Herman, Mark','18-06-1991','71');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jones, Terry','19-06-1991','72');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zanussi, Krzystoff','20-06-1991','73');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Blancato, Ken','21-06-1991','74');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dell, Stewart','22-06-1991','75');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Keshishian, Alek','23-06-1991','76');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Loncraine, Richard','24-06-1991','77');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lanza, Anthony M.','25-06-1991','78');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lewis, Joseph H.','26-06-1991','79');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gold, Greg','27-06-1991','80');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Deruddere, Dominique','28-06-1991','81');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('George, Peter','29-06-1991','82');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Landis, John','30-06-1991','83');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Donner, Clive','01-07-1991','84');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Paris, Jerry','02-07-1991','85');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Palcy, Euzhan','03-07-1991','86');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bunuel, Luis','04-07-1991','87');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Beebe, Ford','05-07-1991','88');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Betnel, Jonathan','06-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Carlsen, Henning','07-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Houck, Joy, Jr.','08-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Patterson, Richard','09-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Perier, Etienne','10-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Purcell, Evelyn','11-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Molinaro, Edouard','12-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Moxey, John Llewellyn','13-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clark, Jim','14-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rappeneau, Jean-Paul','15-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Scott, Ridley','16-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cabanne, Christy','17-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clément, René','18-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Theumer, Ernst R. von','19-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rifkin, Adam','20-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Panama, Norman','21-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Avedis, Howard Hikmet','22-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cocteau, Jean','23-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Roeg, Nicolas','24-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kiersch, Fritz','25-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('De Palma, Brian','26-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Seltzer, David','27-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zieff, Howard','28-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Reeve, Geoffrey','29-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wilmington, Michael','30-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Browning, Tod','31-07-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Chaffey, Don','01-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Meyer, Nicholas','02-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cornell, John','03-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jarmusch, Jim','04-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hill, Walter','05-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lommel, Ulli','06-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Beaudine, William','07-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Weis, Gary','08-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bennett, Walter','09-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ludwig, Edward','10-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cooper, Jackie','11-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jackson, Donald G','12-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Green, Alfred E.','13-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mate, Rudolph','14-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Antonio, Lou','15-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fincher, David','16-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wolfe, Donald','17-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Forsyth, Bill','18-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hellman, Monte','19-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lucidi, Maurizio','20-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('MacNaughton, Ian','21-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Nigh, William','22-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Szwarc, Jeannot','23-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Glaser, Paul Michael','24-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Frankenheimer, John','25-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wenders, Wim','26-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Surin, Fred','27-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mastorakis, Nico','28-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rush, Richard','29-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Edgren, Gustaf','30-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pevney, Joseph','31-08-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ingvordsen, J. Christian','01-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cannon, Dyan','02-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Huyck, Willard','03-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('S, Jeremiah','04-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Aldrich, Robert','05-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Goulding, Edmund','06-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wrede, Caspar','07-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Menendez, Ramon','08-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pollack, Sydney','09-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kane, Joseph','10-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Collins, Lewis D.','11-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gilbert, Brian','12-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pabst, Georg Wilhelm','13-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pytka, Joe','14-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Haskin, Byron','15-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Levinson, Barry','16-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Byrum, John','17-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Katselas, Milton','18-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Marshall, Garry','19-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kazan, Elia','20-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Magnoli, Albert','21-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McBride, Jim','22-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Webb, Millard','23-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kikoine, Gerard','24-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Coppola, Christopher','25-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Malmuth, Bruce','26-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Estevez, Emilio','27-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mann, Daniel','28-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Fraker, William A.','29-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lovy, Steven','30-09-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Reiner, Carl','01-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Annaud, Jean-Jacques','02-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jordan, Glenn','03-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Gillard, Stuart','04-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Heisler, Stuart','05-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Morrissey, Paul','06-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Simon, S. Sylvan','07-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Becker, Harold','08-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jarman, Derek','09-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mackendrick, Alexander','10-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pyun, Albert','11-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Quine, Richard','12-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rochlin, Sheldon','13-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Gavin','14-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wayne, John','15-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Veber, Francis','16-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Malick, Terrence','17-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bergman, Ingmar','18-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lang, Fritz','19-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Malle, Louis','20-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Joanou, Phil','21-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Friedkin, William','22-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Seiter, William A.','23-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Crichton, Charles','24-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Franklin, Howard ','25-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Richards, Dick','26-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Caro, Marc','27-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Casden, Ron','28-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lucas, George','29-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Marquand, Richard','30-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Demme, Jonathan','31-10-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McEveety, Bernard','01-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lubitsch, Ernst','02-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Robertson, John S.','03-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Davis, Andrew','04-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Harvey, Anthony','05-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rydell, Mark','06-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mazursky, Paul','07-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Barrett, Lezli-An','08-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cox, Alex','09-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hough, John','10-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mattoli, Mario','11-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bergman, Andrew','12-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Minnelli, Vincente','13-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Dearden, Basil','14-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Thomas, Dave','15-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Waggner, George','16-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bonerz, Peter','17-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Segal, Alex','18-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Spottiswoode, Roger','19-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Schlöndorff, Volker','20-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kadar, Jan','21-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Losey, Joseph','22-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hulton, Brian G.','23-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Plone, Allen','24-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jeunet, Jean-Pierre','25-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Allen, Craig','26-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Anderson, Michael','27-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Boulting, John','28-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('De Bello, John','29-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hardy, Rod','30-11-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Heyes, Douglas','01-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Leo, Malcolm','02-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Oliver, Ron','03-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Taylor, Roderick','04-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Almodóvar, Pedro','05-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Seidelman, Susan','06-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wellman, William','07-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kershner, Irvin','08-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rafelson, Bob','09-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bernds, Edward','10-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Pialat, Maurice','11-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('McTiernan, John','12-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ford, Aleksander','13-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lambert, Bruce','14-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Daniel, Rod','15-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Budds, Colin','16-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Stein, Ken','17-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Sheridan, Jim','18-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cassavetes, John','19-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Beresford, Bruce','20-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Welles, Orson','21-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clarke, Alan','22-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hooks, Kevin','23-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Bogdanovich, Peter','24-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('King, Henry','25-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Faiman, Peter','26-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mizoguchi, Kenji','27-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Weir, Peter','28-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Howard, William K.','29-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ferrera, Abel','30-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kaplan, Jonathan','31-12-1991','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Haggard, Piers','01-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Zucker, Jerry','02-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Cammell, Donald','03-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Masterson, Peter','04-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Ivory, James','05-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Compton, Richard','06-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Towne, Robert','07-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Baker, Graham','08-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Reitman, Ivan','09-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rohmer, Eric','10-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Imamura, Shohei','11-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Finkleman, Ken','12-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Rosenthal, Rick','13-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Wharmby, Tony','14-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Towns, Philip Saville','15-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Mandel, Robert','16-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Marshall, George','17-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Farrow, John','18-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Kronsberg, Jeremy Joe','19-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Roth, Bobby','20-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Hancock, John D.','21-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Annakin, Ken','22-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Clair, Rene','23-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Jackson, Mick','24-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Lennon, Biddy W.','25-01-1992','150');
INSERT INTO registi( nominativo, data_nascita,paese_di_origine) VALUES ('Werner, Peter','26-01-1992','147');
