INSERT INTO paesi(ID_TEC,ANNO,TECNOLOGIA)VALUES ('1','1973','IMAX Dome');
INSERT INTO paesi(ID_TEC,ANNO,TECNOLOGIA)VALUES ('2','2012','IMAX 3D');
INSERT INTO paesi(ID_TEC,ANNO,TECNOLOGIA)VALUES ('3','1992','IMAX HD');
INSERT INTO paesi(ID_TEC,ANNO,TECNOLOGIA)VALUES ('4','2008','IMAX Digitale');
INSERT INTO paesi(ID_TEC,ANNO,TECNOLOGIA)VALUES ('5','2014','IMAX Laser');
INSERT INTO paesi(ID_TEC,ANNO,TECNOLOGIA)VALUES ('6','2011','IMAX 3D Digital Camera');
INSERT INTO paesi(ID_TEC,ANNO,TECNOLOGIA)VALUES ('7','2015','ARRI ALEXA IMAX');