INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Travolta','1954-02-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kirstie Alley','1951-01-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Olympia Dillakis','1931-06-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('George Segal','1934-02-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Abe Vigoda','1921-02-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bruce Willis','1955-03-19','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Twink Caplan','1947-12-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Schaller','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jaryd Waterhouse','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Morgan Freeman','1937-06-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jessica Tandy','1909-06-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dan Aykroyd','1952-07-01','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patti LuPone','1949-04-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Esther Rolle','1920-11-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jo Ann Havrilla','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('William Hall Jr.','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alvin M. Sugarman','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Clarice F. Geigerman','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Cruise','1962-07-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bryan Larkin','1973-08-07','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Raymond J. Barry','1939-03-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Caroline Kava','1949-09-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Josh Evans','1971-01-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Seth Allen','1941-07-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jamie Talisman','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Stone','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anne Bobby','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Costner','1955-01-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Amy Madigan','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gaby Hoffmann','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ray Liotta','1954-12-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Timothy Busfield','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Earl Jones','1931-01-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Burt Lancaster','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Frank Whaley','1963-07-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dwier Brown','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Candy','1950-10-31','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jean Louisa Kelly','1972-03-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Macaulay Culkin','1980-08-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elaine Bromka','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Garrett M. Brown','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Laurie Metcalf','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jay Underwood','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Crystal','1948-03-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Meg Ryan','1961-11-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Carrie Fisher','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bruno Kirby','1949-04-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Steven Ford','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lisa Jane Persky','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michelle Nicastro','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gretchen Palmer','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Alan Beuth','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robin Williams','1951-07-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Sean Leonard','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ethan Hawke','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Josh Charles','1971-09-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gale Hansen','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dylan Kussman','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Allelon Ruggiero','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Waterston','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Norman Lloyd','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Steve Martin','1945-08-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mary Steenburgen','1953-02-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dianne Wiest','1948-03-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Robards','1992-07-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rick Moranis','1953-04-18','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Hulce','1953-12-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Martha Plimpton','1960-11-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Keanu Reeves','1964-09-02','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harley Jane Kozak','1957-01-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mel Gibson','1956-01-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Danny Glover','1946-07-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joe Pesci','1943-02-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joss Ackland','1928-02-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Derrick O''Connor','1941-01-03','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patsy Kensit','1968-03-04','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Darlene Love','1938-07-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Traci Wolfe','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Steve Kahan','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Douglas','1944-09-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kathleen Turner','1954-06-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Danny DeVito','1944-11-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Marianne Sgebrecht','1944-11-17','67');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Astin','1971-02-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Heather Fairfield','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('G.D. Spradlin','1920-08-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Donat','1960-12-11','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dan Castellaneta','1957-10-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Chevy Chase','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Beverly D''Angelo','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Juliette Lewis','1973-06-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Johnny Galecki','1975-04-30','Belgium');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Randolph','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Diane Ladd','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('E.G. Marshall','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Doris Roberts','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Randy Quaid','1950-10-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Matt Frewer','1958-01-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Marcia Strassman','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kristine Sutherland','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Thomas Wilson Brown','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jared Rushton','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Amy O''Neill','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Oliveri','1978-04-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Carl Steven','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Keaton','1951-09-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jack Nicholson','1937-04-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kim Basinger','1953-12-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Wuhl','1951-10-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Pat Hingle','1924-07-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Dee Williams','1937-04-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Gough','1916-11-23','British Malaya');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jack Palance','1920-02-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jerry Hall','1956-07-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bill Murray','1950-09-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sigourney Weaver','1949-10-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harold Ramis','1944-11-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ernie Hudson','1945-12-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Annie Potts','1952-10-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter MacNicol','1954-04-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harris Yulin','1937-11-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rene Auberjonois','1940-06-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher Daniel Barnes','1972-11-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jodi Benson','1961-10-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Pat Carroll','1927-05-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Paddi Edwards','1931-03-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Buddy Hackett','1924-08-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Marin','1974-07-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kenneth Mars','1935-04-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Edie McClurg','1945-07-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael J. Fox','1961-06-09','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher Lloyd','1938-10-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lea Thompson','1961-05-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Thomas F. Wilson','1959-04-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elisabeth Shue','1963-10-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Tolkan','1931-06-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeffrey Weissman','1958-10-02','');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Casey Siemaszko','1961-03-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Zane','1966-02-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harrison Ford','1942-07-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Connery','1930-08-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Denholm Elliott','1922-05-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alison Doody','1966-11-11','Ireland');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Rhys-Davies','1944-05-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Julian Glover','1935-03-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('River Phoenix','1970-08-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Byrne','1943-11-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sally Field','1946-11-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dolly Parton','1946-01-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Shirley MacLaine','1934-04-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Daryl Hannah','1960-12-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Julia Roberts','1967-10-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Skerritt','1933-08-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sam Shepard','1943-11-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dylan McDermott','1961-10-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Judith Hoag','1968-06-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elias Koteas','1961-03-11','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Josh Pais','1958-06-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brian Tochi','1959-05-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Leif Tilden','1964-03-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Corey Feldman','1971-07-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michelan Sisti','1949-05-27','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robbie Rist','1964-04-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Gere','1949-08-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ralph Bellamy','1904-06-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Alexander','1959-09-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Laura San Giacomo','1962-11-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alex Hyde-White','1959-01-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Amy Yasbeck','1962-09-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elinor Donahue','1937-04-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Hector Elizondo','1936-12-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Arnold Schwarzenegger','1947-07-30','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Penelope Ann Miller','1964-01-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Pamela Reed','1949-04-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Linda Hunt','1945-04-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Tyson','1961-02-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Carroll Baker','1931-05-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joseph Cousins','1983-03-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christian Cousins','1983-03-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Cathy Moriarty','1960-11-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Daniel Stern','1957-08-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Heard','1946-03-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Roberts Blossom','1924-03-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Angela Goethals','1977-05-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Devin Ratray','1977-01-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gerry Bamman','1941-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Goldie Hawn','1945-11-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Carradine','1936-12-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bill Dille','1943-02-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stephen Tobolowsky','1951-05-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joan Severance','1958-12-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harry Caesar','1928-02-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeff Corey','1914-08-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alex Bruhanski','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Caan','1940-03-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kathy Bates','1948-06-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Farnsworth','1920-09-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Frances Sternhagen','1930-01-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lauren Bacall','1924-09-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Graham Jarvis','1930-08-25','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jerry Potter','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Thomas Brunelle','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('June Christopher','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Johnny Depp','1963-06-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Winona Ryder','1971-10-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anthony Michael Hall','1968-04-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kathy Baker','1950-06-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Conchata Ferrell','1943-03-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Caroline Aaron','1952-08-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dick Anthony Williams','1934-08-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patrick Swayze','1952-08-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Demi Moore','1962-11-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tony Goldwyn','1960-05-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stanley Lawrence','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher J. Keene','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Silln Breslau','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rick Kleber','1957-05-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Macka Foley','1951-01-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brian Dennehy','1938-07-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Raul Julia','1940-03-09','Puerto Rico');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bonnie Bedelia','1948-03-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Paul Winfield','1939-05-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Greta Scacchi','1960-02-18','Italy');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Spencer','1946-12-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joe Grifasi','1944-06-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Mardirosian','1947-12-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mary McDonnell','1952-04-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Graham Greene','1952-06-22','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rodney A. Grant','1959-03-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Floyd ''Red Crow'' Westerman','1936-08-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tantoo Cardinal','1950-07-20','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Pastorelli','1954-06-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Charles Rocket','1949-08-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Maury Chaykin','1949-07-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kiefer Sutherland','1966-12-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Bacon','1958-07-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('William Baldwin','1963-02-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Oliver Platt','1960-01-12','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kimberly Scott','1961-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joshua Rudoy','1975-12-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Benjamin Mouton','1965-03-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Aeryk Egan','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alec Baldwin','1958-04-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Scott Glenn','1939-01-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sam Neill','1947-09-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Jordan','1937-07-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Firth','1953-10-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tim Curry','1946-04-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Eddie Murphy','1961-04-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Nick Nolte','1941-02-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brion James','1945-02-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Tighe','1944-08-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ed O''Ross','1949-07-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Andrew Divoff','1955-07-02','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bernie Casey','1939-06-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Matt Clark','1936-11-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Dysart','1929-03-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Pat Buttram','1915-06-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Warren Beatty','1937-03-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Charlie Korsmo','1978-07-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Donovan O''Donnell','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jim Wilkey','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stig Eldred','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Neil Summers','1944-04-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Chuck Hicks','1927-12-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('William Forsythe','1955-06-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Al Pacino','1940-04-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Diane Keaton','1946-01-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Talia Shire','1946-04-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Andy Garcia','1956-04-12','Cuba');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Eli Wallach','1915-12-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joe Mantegna','1947-11-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('George Hamilton','1939-08-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bridget Fonda','1964-01-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sofia Coppola','1971-05-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Nicole Kidman','1967-06-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Duvall','1931-01-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Cary Elwes','1962-10-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Rooker','1955-04-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Fred Dalton Thompson','1942-08-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John C. Reilly','1965-05-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('J.C. Quinn','1940-11-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rachel Ticotin','1958-11-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sharon Stone','1958-03-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ronny Cox','1938-07-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Ironside','1950-02-12','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Marshall Bell','1942-09-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mel Johnson Jr.','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Roy Brocksmith','1945-09-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('William Atherton','1947-07-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Reginald VelJohnson','1952-08-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Franco Nero','1941-11-23','Italy');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('William Sadler','1950-04-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Amos','1939-12-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dennis Franz','1944-10-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Art Evans','1942-03-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mary Stuart Masterson','1966-06-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mary-Louise Parker','1964-08-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Cicely Tyson','1924-12-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Chris O''Donnell','1970-06-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stan Shaw','1952-07-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gailard Sartain','1946-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Timothy Scott','1937-07-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jodie Foster','1962-11-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lawrence A. Bonney','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kasi Lemmons','1961-02-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anthony Heald','1944-08-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Frankie Faison','1949-06-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Don Brockett','1930-01-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Frank Seals Jr.','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patrick Bergin','1951-02-04','Ireland');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Anderson','1960-01-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elizabeth Lawrence','1922-09-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kyle Secor','1957-05-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Claudette Nevins','1937-04-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Marita Geraghty','1962-03-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harley Venton','1953-11-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kimberly Williams-Paisley','1971-09-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kieran Culkin','1982-09-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('George Newbern','1964-12-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Martin Short','1950-03-26','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('BD Wong','1960-10-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Michael Goetz','1941-12-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kate McGregor-Stewart','1944-10-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robby Benson','1956-01-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rex Everhart','1920-06-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Angela Lansbury','1925-10-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Paige Oì''Hara','1956-05-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Ogden Stiers','1942-10-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard White','1953-08-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Charlie Sheen','1965-09-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Valeria Golino','1965-10-22','Italy');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lloyd Bridges','1913-01-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Dunn','1956-08-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jon Cryer','1965-04-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Laurel Cronin','1939-10-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kurt Russell','1951-03-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Donald Sutherland','1935-07-17','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jennifer Jason Leigh','1962-02-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rebecca De Mornay','1959-08-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Gedrick','1965-02-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('J.T. Walsh','1943-09-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Linda Hamilton','1956-09-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Edward Furlong','1977-08-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Patrick','1958-11-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Earl Boen','1941-08-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joe Morton','1947-10-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('S. Epatha Merkerson','1952-11-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Castulo Guerra','1945-08-24','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Danny Cooksey','1975-11-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Forest Whitaker','1961-07-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Miranda Richardson','1958-03-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stephen Rea','1946-10-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Adrian Dunbar','1958-08-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Breffni McKenna','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joe Savino','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Birdy Sweeney','1931-06-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jaye Davidson','1968-03-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Andre Bernard','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Clint Eastwood','1930-05-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gene Hackman','1930-01-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Harris','1930-10-01','Ireland');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jaimz Woolvett','1967-04-14','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Saul Rubinek','1948-07-02','67');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Frances Fisher','1952-05-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anna Levine','1953-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Mucci','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Hillary Wolf','1977-02-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Maureen Elisabeth Shay','1978-05-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael C. Maronna','1977-09-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mike Myers','1963-05-25','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dana Carvey','1955-06-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rob Lowe','1964-03-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tia Carrere','1967-01-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brian Doyle-Murray','1945-10-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lara Flynn Boyle','1970-03-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael DeLuise','1969-08-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dan Bell','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lee Tergesen','1965-07-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Whitney Houston','1963-08-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gary Kemp','1959-10-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bill Cobbs','1934-06-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ralph Waite','1928-06-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tomas Arana','1955-04-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michele Lamar Richards','1954-11-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mike Starr','1950-07-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Portnow','1947-12-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Rebhorn','1948-09-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gabrielle Anwar','1970-02-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Philip Seymour Hoffman','1967-07-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Venture','1923-11-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bradley Whitford','1959-10-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rochelle Oliver','1937-04-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Margaret Eginton','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rene Russo','1954-02-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stuart Wilson','1946-12-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Damon Hines','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Steven Seagal','1952-04-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Damian Chapa','1963-10-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Troy Evans','1948-02-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David McKnight','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lee Hinton','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Megan Cavanagh','1960-11-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tracy Reiner','1964-07-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bitty Schram','1968-07-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ann Cillck','1961-05-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Daniel Day-Lewis','1957-04-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Madeleine Stowe','1958-08-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Russell Means','1939-11-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Eric Schweig','1967-06-19','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jodhi May','1975-05-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Steven Waddington','1967-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Wes Studi','1947-12-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Maurice Roeves','1937-03-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patrice Chereau','1944-11-02','70');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gary Oldman','1958-03-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anthony Hopkins','1937-12-31','70');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard E. Grant','1957-05-05','70');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Campbell','1959-07-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sadie Frost','1965-06-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Waits','1949-12-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Pollak','1957-10-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Marshall','1967-01-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher Guest','1948-02-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anne Archer','1947-08-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Bean','1959-04-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Thora Birch','1982-03-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Fox','1939-05-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Samuel L. Jackson','1948-12-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Polly Walker','1966-05-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('J.E. Freeman','1946-02-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('George Dzundza','1945-07-19','67');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeanne Tripplehorn','1963-06-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Denis Arndt','1939-02-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Leilani Sarelle','1966-09-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Chelcie Ross','1942-10-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dorothy Malone','1924-01-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michelle Pfeiffer','1958-04-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher Walken','1943-03-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Murphy','1938-05-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Cristi Conaway','1964-08-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Andrew Bryniarski','1969-02-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Leon','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Doug E. Doug','1970-01-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rawle D. Lewis','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Malik Yoba','1967-09-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Outerbridge','1966-06-30','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Larry Gilman','1950-04-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Andie MacDowell','1958-04-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Chris Elliott','1960-05-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Angela Paton','1930-01-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rick Ducommun','1952-07-03','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rick Overton','1954-08-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason James Richter','1980-01-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jayne Atkinson','1959-02-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('August Schellenberg','1936-07-25','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Madsen','1957-09-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Riehle','1948-05-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mykelti Williamson','1957-03-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Bacall','1973-04-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ross Malinger','1984-07-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rita Wilson','1956-10-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Victor Garber','1949-03-16','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Riis Farrell','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Carey Lowell','1961-02-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bill Pullman','1953-12-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Liam Neeson','1952-06-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ben Kingsley','1943-12-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ralph Fiennes','1962-12-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jonathan Sagall','1959-04-23','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Embeth Davidtz','1965-08-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Malgorzata Gebel','1955-11-30','Poland');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Shmuel Levy','1962-12-04','Israel');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mark Ivanir','1968-09-06','illraine');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Pierce Brosnan','1953-05-16','Ireland');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harvey Fierstein','1954-06-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Polly Holliday','1937-07-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lisa Jakub','1978-12-27','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Matthew Lawrence','1980-02-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mara Wilson','1987-07-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Prosky','1930-12-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Val Kilmer','1959-12-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sam Elliott','1944-08-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bill Paxton','1955-05-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Powers Boothe','1948-06-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Biehn','1956-07-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Charlton Heston','1923-10-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Priestley','1969-08-28','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jon Tenney','1961-12-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Denzel Washington','1954-12-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Roberta Maxwell','1941-06-17','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Buzz Kilman','1944-08-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Karen Finley','1956-03-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mark Sorensen Jr.','1962-03-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeffrey Williamson','1965-06-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Charles Glenn','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Kline','1947-10-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Frank Langella','1938-01-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ving Rhames','1959-05-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Charles Grodin','1935-04-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Faith Prince','1957-08-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Laura Linney','1964-02-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jack Lemmon','1925-02-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Walter Matthau','1920-10-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ann-Margret','1941-04-28','172');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Burgess Meredith','1907-11-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ossie Davis','1917-12-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Buck Henry','1930-12-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher McDonald','1955-02-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Redford','1936-08-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Seymour Cassel','1935-01-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Bob Thornton','1955-08-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rip Taylor','1931-01-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Connolly','1942-11-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joel Brooks','1949-12-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Barnard Hughes','1915-07-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Coburn','1928-08-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Jeter','1952-08-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sheryl Lee Ralph','1956-12-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Malkovich','1953-12-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gary Cole','1956-09-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Mahoney','1940-06-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gregory Alan Williams','1956-06-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jim Curley','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Cary-Hiroyilli Tagawa','1950-09-27','70');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mako','1933-12-10','70');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ray Wise','1947-08-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Hal Holbrook','1925-02-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Terry Kinney','1954-01-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Wilford Brimley','1934-09-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ed Harris','1950-11-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Holly Hunter','1958-03-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Strathairn','1949-01-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tommy Lee Jones','1946-09-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sela Ward','1956-07-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Julianne Moore','1960-12-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joe Pantoliano','1951-09-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Andreas Katsulas','1946-05-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Daniel Roebuck','1963-03-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('L. Scott Caldwell','1950-04-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Sikking','1934-03-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Culp','1930-08-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stanley Tucci','1960-11-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sylvester Stallone','1946-07-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sandra Bullock','1964-07-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Nigel Hawthorne','1929-04-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Benjamin Bratt','1963-12-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bob Gunton','1945-11-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Glenn Shadix','1952-04-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Denis Leary','1957-08-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Grand L. Bush','1955-12-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Lithgow','1945-10-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Janine Turner','1962-12-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rex Linn','1956-11-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Craig Fairbrass','1964-12-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gregory Scott Cummins','1956-12-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tim Roth','1961-05-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Amanda Plummer','1957-03-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Laura Lovelace','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Phil LaMarr','1967-01-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jim Carrey','1962-01-17','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Courteney Cox','1964-06-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Young','1959-11-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tone Loc','1966-03-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dan Marino','1961-09-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Raynor Scheine','1942-01-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Udo Kier','1944-10-14','67');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeff Daniels','1955-02-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lauren Holly','1963-10-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Karen Duffy','1962-05-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Victoria Rowell','1959-05-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joe Baker','1928-12-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Hank Brandt','1934-06-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tim Allen','1953-06-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Judge Reinhold','1957-05-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Wendy Crewson','1956-05-09','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Eric Lloyd','1986-05-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Krumholtz','1978-05-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Larry Brandenburg','1948-05-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mary Gross','1953-03-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Paige Tamada','1985-01-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Boyle','1935-10-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Riegert','1947-04-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Greene','1965-10-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Jeni','1957-04-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Orestes Matacena','1941-08-29','Cuba');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tim Bagley','1957-08-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Nancy Fish','1938-03-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Johnny Williams','1932-02-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dennis Hopper','1936-05-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alan Ruck','1956-07-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Glenn Plummer','1961-08-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Lineback','1952-02-04','67');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Beth Grant','1949-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brad Pitt','1963-12-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Aidan Quinn','1959-03-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Julia Ormond','1965-01-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Henry Thomas','1971-09-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Karina Lombard','1969-01-21','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gordon Tootoosis','1941-10-25','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Paul Desmond','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rowan Atkinson','1955-01-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Matthew Broderick','1962-03-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Niketa Calame-Harris','1980-11-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jim Cummings','1952-11-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Guillaume','1927-11-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeremy Irons','1948-09-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Moira Kelly','1968-03-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Silln Sarandon','1946-10-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anthony LaPaglia','1959-01-31','11');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anthony Edwards','1962-07-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brad Renfro','1982-07-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Will Patton','1954-06-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Woods','1947-04-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rod Steiger','1925-04-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Eric Roberts','1956-04-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mario Ernesto Snchez','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sergio Dor Jr.','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Chase Randolph','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeana Bell','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Goodman','1952-06-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elizabeth Perkins','1960-11-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kyle MacLachlan','1959-02-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elizabeth Taylor','1932-02-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dann Florek','1950-05-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Moll','1943-01-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rebecca Williams','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Conner Humphreys','1985-12-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harold G. Herthum','1929-04-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('George Kelly','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bob Penny','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Randall','1914-12-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sam Anderson','1984-12-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Spader','1960-02-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Viveca Lindfors','1920-12-29','172');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alexis Cruz','1974-09-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mili Avital','1972-03-30','Israel');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Leon Rippy','1949-10-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Diehl','1950-05-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Roma Maffia','1958-05-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dylan Baker','1959-10-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rosemary Forsyth','1943-07-06','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dennis Miller','1934-04-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Suzie Plakson','1958-06-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Willem Dafoe','1955-07-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joaquim de Almeida','1957-03-15','142');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Henry Czerny','1959-02-08','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Donald Moffat','1930-12-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Miguel Sandoval','1951-11-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Jenkins','1947-05-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher Plummer','1929-12-13','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Eileen Atkins','1934-06-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Hyde Pierce','1959-04-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Om Puri','1950-10-18','India');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Garner','1928-04-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alfred Molina','1953-05-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dub Taylor','1907-02-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Geoffrey Lewis','1935-07-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Paul L. Smith','1936-06-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jamie Lee Curtis','1958-11-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Arnold','1959-03-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Art Malik','1952-11-13','135');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Eliza Dushku','1980-12-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Grant Heslov','1963-05-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Gallagher','1955-08-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jack Warden','1920-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Glynis Johns','1923-10-05','168');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Micole Mercurio','1938-03-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Bernard','1938-05-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Rispoli','1960-11-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Courtney B. Vance','1960-03-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robin Bartlett','1951-04-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Beatrice Winde','1924-01-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Neville','1925-05-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lorraine Toussaint','1960-04-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Renoly Santiago','1974-03-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Wade Dominguez','1966-05-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sophia Loren','1934-09-20','Italy');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Katie Sagona','1989-11-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ann Morgan Guilbert','1928-10-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Don Rickles','1926-05-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jim Varney','1949-06-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Wallace Shawn','1943-11-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Ratzenberger','1947-04-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Erik von Detten','1982-10-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ian McNeice','1950-10-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Simon Callow','1949-06-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Maynard Eziashi','1965-12-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sophie Okonedo','1968-08-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tommy Davidson','1963-11-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Adewale Akinnuoye-Agbaje','1967-08-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Danny Daniels','1927-11-01','168');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dennis Farina','1944-02-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Delroy Lindo','1952-11-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Gandolfini','1961-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jon Gries','1957-06-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Renee Props','1962-02-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Glenne Headly','1955-03-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jay Thomas','1948-07-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('William H. Macy','1950-03-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alicia Witt','1975-08-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Terrence Howard','1969-03-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Damon Whitaker','1970-10-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Andrew Kevin Walker','1964-08-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Daniel Zacapa','1951-07-19','');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gwyneth Paltrow','1972-09-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Cassini','1999-12-12','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bob Mack','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Crombie','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Reg E. Cathey','1958-08-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Malachi Pearson','1981-06-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Eric Idle','1943-03-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ben Stein','1944-11-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Don Novello','1943-01-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Fred Rogers','1928-03-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Emily Ann Lloyd','1984-03-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Miko Hughes','1986-02-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Matt Craven','1956-11-10','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Viggo Mortensen','1958-10-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rocky Carroll','1963-07-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jaime Gomez','1965-08-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Milhoan','1957-12-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christian Bale','1974-01-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Irene Bedard','1967-07-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ralph Riach','1939-12-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Drew Barrymore','1975-02-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Debi Mazar','1964-08-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Chaim Jeraffi','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rick Aviles','1952-10-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('R.D. Call','1996-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Zitto Kazann','1944-09-01','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Leonardo Cimino','1917-11-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Zakes Mokae','1934-08-05','168');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lille Ka''ili Jr.','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anthony DeMasters','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Roger Jackson','1958-07-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Patrick Walls','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Booth','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Carla Hatley','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Neve Campbell','1973-10-03','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Skeet Ulrich','1970-01-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lawrence Hecht','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bette Midler','1945-12-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sarah Jessica Parker','1965-03-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stockard Channing','1944-02-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stephen Collins','1947-10-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Juliette Binoche','1964-03-09','France');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kristin Scott Thomas','1960-05-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Naveen Andrews','1969-01-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Colin Firth','1960-09-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Julian Wadham','1958-08-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jrgen Prochnow','1941-06-10','67');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Whately','1951-02-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Nathan Lane','1956-02-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dan Futterman','1967-06-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Calista Flockhart','1964-11-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Hank Azaria','1964-04-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christine Baranski','1952-05-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom McGowan','1959-07-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kyra Sedgwick','1965-08-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeffrey DeMunn','1947-04-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Kiley','1922-03-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Gallagher','1985-02-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ashley Buccille','1986-01-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tony Genaro','1941-10-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Matthew McConaughey','1969-11-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Spacey','1959-07-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Charles S. Dutton','1951-01-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brenda Fricker','1945-02-17','Ireland');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patrick Stewart','1940-07-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jonathan Frakes','1952-08-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brent Spiner','1949-02-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('LeVar Burton','1957-02-16','67');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Dorn','1952-12-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gates McFadden','1949-03-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Marina Sirtis','1955-03-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alfre Woodard','1952-11-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Cromwell','1940-01-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Samantha Mathis','1970-05-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Howie Long','1960-01-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Vondie Curtis-Hall','1950-09-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jack Thompson','1940-08-31','11');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Cuba Gooding Jr.','1968-01-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Renee Zellweger','1969-04-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kelly Preston','1962-10-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jerry O''Connell','1974-02-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jay Mohr','1970-08-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Regina King','1971-01-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jonathan Lipnicki','1990-10-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jada Pinkett Smith','1971-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Larry Miller','1953-10-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dave Chappelle','1973-08-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Ales','1969-01-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patricia Wilson','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Glenn Close','1947-03-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joely Richardson','1965-01-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joan Plowright','1929-10-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Hugh Laurie','1959-06-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mark Williams','1959-08-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Shrapnel','1942-04-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tim McInnerny','1956-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Hugh Fraser','1945-10-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Nicolas Cage','1964-01-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Morse','1953-10-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Vanessa Marcil','1968-10-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John C. McGinley','1959-08-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Will Smith','1968-09-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeff Goldblum','1952-10-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Judd Hirsch','1935-03-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Loggia','1930-01-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Margaret Colin','1958-05-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jon Voight','1938-12-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Emmanuelle Bart','1963-08-14','France');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Vanessa Redgrave','1937-01-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ingeborga Dapkunaite','1963-01-20','148');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brawley Nolte','1986-06-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lili Taylor','1967-02-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Liev Schreiber','1967-10-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Donnie Wahlberg','1969-08-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Evan Handler','1961-01-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Jordan','1987-02-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Wayne Knight','1955-08-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Theresa Randle','1964-12-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Manner Washington','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Penny Bae Bridges','1990-07-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brandon Hammond','1984-02-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Larry Bird','1956-12-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Helen Hunt','1963-06-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jami Gertz','1965-10-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lois Smith','1930-11-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Whalen','1964-05-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Scott Thomson','1957-10-29','');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mary Kay Bergman','1961-06-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Corey Burton','1955-08-03','144');


