INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 1A', '110', '2', '100');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 1B', '110', '3', '100');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 1C', '110', '4', '100');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 1D', '110', '3', '150');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 1E', '110', '3', '150');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 2A', '110', '3', '50');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 2B', '110', '2', '50');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 2C', '110', '2', '50');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ( 'SALA 2D', '110', '2', '50');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('SALA 2E', '110', '2', '100');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('SALA 3A', '110', '4', '25');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('SALA 3B', '110', '4', '25');
INSERT INTO sale( descrizione, sistema_audio, tecnologia_proiezione, posti)	VALUES ('SALA 3C', '110', '4', '25');
