INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('1','Look Who''s Talking','1989','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('2','Driving Miss Daisy','1989','1','99');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('3','Turner & Hooch','1989','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('4','Born on the Fourth of July','1989','1','145');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('5','Field of Dreams','1989','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('6','Uncle Buck','1989','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('7','When Harry Met Sally...','1989','1','96');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('8','Dead Poets Society','1989','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('9','Parenthood','1989','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('10','Lethal Weapon 2','1989','1','114');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('11','The War of the Roses','1989','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('12','National Lampoon''s Christmas Vacation','1989','1','97');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('13','Honey I Shrunk the Kids','1989','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('14','Batman','1989','1','126');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('15','Ghostbusters II','1989','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('16','The Little Mermaid','1989','1','83');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('17','Back to the Future Part II','1989','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('18','Indiana Jones and the Last Crusade','1989','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('19','Tango & Cash','1989','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('20','Steel Magnolias','1989','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('21','Three Men and a Little Lady','1990','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('22','Teenage Mutant Ninja Turtles','1990','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('23','Pretty Woman','1990','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('24','Kindergarten Cop','1990','1','111');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('25','Home Alone','1990','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('26','Bird on a Wire','1990','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('27','Misery','1990','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('28','Edward Scissorhands','1990','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('29','Ghost','1990','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('30','Presumed Innocent','1990','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('31','Dances with Wolves','1990','1','181');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('32','Flatliners','1990','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('33','The Hunt for Red October','1990','1','134');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('34','Another 48 Hrs.','1990','1','95');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('35','Back to the Future Part III','1990','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('36','Dick Tracy','1990','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('37','The Godfather: Part III','1990','1','162');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('38','Days of Thunder','1990','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('39','Total Recall','1990','1','113');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('40','Die Hard 2','1990','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('41','Fried Green Tomatoes','1991','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('42','The Silence of the Lambs','1991','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('43','Sleeping with the Enemy','1991','1','99');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('44','Father of the Bride','1991','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('45','The Naked Gun 2 1/2: The Smell of Fear','1991','1','85');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('46','Teenage Mutant Ninja Turtles II','1991','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('47','Beauty and the Beast','1991','1','84');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('48','Hot Shots!','1991','1','84');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('49','City Slickers','1991','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('50','Star Trek VI: The Undiscovered Country','1991','1','113');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('51','The Addams Family','1991','1','99');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('52','The Prince of Tides','1991','1','132');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('53','What About Bob?','1991','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('54','Cape Fear','1991','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('55','JFK','1991','1','189');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('56','Robin Hood: Prince of Thieves','1991','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('57','Hook','1991','1','144');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('58','Backdraft','1991','1','137');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('59','Terminator 2: Judgment Day','1991','1','137');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('60','The Crying Game','1992','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('61','The Hand that Rocks the Cradle','1992','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('62','Unforgiven','1992','1','131');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('63','Home Alone 2: Lost in New York','1992','1','120');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('64','Wayne''s World','1992','1','94');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('65','The Bodyguard','1992','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('66','Aladdin','1992','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('67','White Men Can''t Jump','1992','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('68','Sister Act','1992','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('69','Scent of a Woman','1992','1','157');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('70','Lethal Weapon 3','1992','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('71','Under Siege','1992','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('72','Boomerang','1992','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('73','A League of Their Own','1992','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('74','The Last of the Mohicans','1992','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('75','Bram Stoker''s Dracula','1992','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('76','A Few Good Men','1992','1','138');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('77','Patriot Games','1992','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('78','Basic Instinct','1992','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('79','Batman Returns','1992','1','126');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('80','Cool Runnings','1993','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('81','Groundhog Day','1993','1','101');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('82','Free Willy','1993','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('83','Sleepless in Seattle','1993','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('84','Schindler''s List','1993','1','195');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('85','Mrs. Doubtfire','1993','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('86','Tombstone','1993','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('87','Philadelphia','1993','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('88','Dave','1993','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('89','Grumpy Old Men','1993','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('90','Indecent Proposal','1993','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('91','Sister Act 2: Back in the Habit','1993','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('92','In the Line of Fire','1993','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('93','Rising Sun','1993','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('94','The Firm','1993','1','154');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('95','The Fugitive','1993','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('96','The Pelican Brief','1993','1','141');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('97','Demolition Man','1993','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('98','Cliffhanger','1993','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('99','Jurassic Park III','2001','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('100','Pulp Fiction','1994','1','154');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('101','Ace Ventura: Pet Detective','1994','1','86');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('102','Dumb and Dumber','1994','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('103','The Santa Clause','1994','1','97');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('104','The Mask','1994','1','101');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('105','Speed','1994','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('106','Legends of the Fall','1994','1','133');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('107','Star Trek: Generations','1994','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('108','The Lion King','1994','1','89');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('109','The Client','1994','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('110','The Specialist','1994','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('111','The Flintstones','1994','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('112','Forrest Gump','1994','1','142');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('113','Stargate','1994','1','121');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('114','Disclosure','1994','1','123');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('115','Interview with the Vampire','1994','1','123');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('116','Clear and Present Danger','1994','1','141');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('117','Wolf','1994','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('118','Maverick','1994','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('119','True Lies','1994','1','141');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('120','While You Were Sleeping','1995','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('121','Dangerous Minds','1995','1','99');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('122','Grumpier Old Men','1995','1','101');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('123','Father of the Bride Part II','1995','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('124','Toy Story','1995','1','81');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('125','Ace Ventura: When Nature Calls','1995','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('126','Get Shorty','1995','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('127','Mr. Holland''s Opus','1995','1','137');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('128','Se7en','1995','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('129','Casper','1995','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('130','Congo','1995','1','109');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('131','Apollo 13','1995','1','140');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('132','Crimson Tide','1995','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('133','Pocahontas','1995','1','81');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('134','GoldenEye','1995','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('135','Jumanji','1995','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('136','Braveheart','1995','1','177');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('137','Die Hard: With a Vengeance','1995','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('138','Batman Forever','1995','1','121');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('139','Waterworld','1995','1','135');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('140','Scream','1996','1','111');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('141','The First Wives Club','1996','1','102');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('142','The English Patient','1996','1','162');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('143','The Birdcage','1996','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('144','Phenomenon','1996','1','123');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('145','A Time to Kill','1996','1','149');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('146','Star Trek: First Contact','1996','1','111');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('147','Broken Arrow','1996','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('148','Jerry Maguire','1996','1','139');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('149','The Nutty Professor','1996','1','95');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('150','101 Dalmatians','1996','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('151','The Rock','1996','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('152','Independence Day','1996','1','145');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('153','Mission: Impossible','1996','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('154','Ransom','1996','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('155','Space Jam','1996','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('156','Twister','1996','1','113');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('157','The Hunchback of Notre Dame','1996','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('158','Eraser','1996','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('159','Michael','1996','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('160','Good Will Hunting','1997','1','126');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('161','I Know What You Did Last Summer','1997','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('162','Scream 2','1997','1','120');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('163','My Best Friend''s Wedding','1997','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('164','Liar Liar','1997','1','86');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('165','As Good as It Gets','1997','1','139');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('166','George of the Jungle','1997','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('167','The Lost World: Jurassic Park','1997','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('168','Con Air','1997','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('169','Conspiracy Theory','1997','1','135');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('170','Face/Off','1997','1','138');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('171','Flubber','1997','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('172','Hercules','1997','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('173','Air Force One','1997','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('174','Men in Black','1997','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('175','Contact','1997','1','150');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('176','Tomorrow Never Dies','1997','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('177','Batman and Robin','1997','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('178','Titanic','1997','1','194');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('179','There''s Something About Mary','1998','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('180','The Waterboy','1998','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('181','Shakespeare in Love','1998','1','122');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('182','The Rugrats Movie','1998','1','79');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('183','Rush Hour','1998','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('184','Stepmom','1998','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('185','Patch Adams','1998','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('186','The Truman Show','1998','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('187','You''ve Got Mail','1998','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('188','Saving Private Ryan','1998','1','169');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('189','The Prince of Egypt','1998','1','99');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('190','Doctor Dolittle','1998','1','85');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('191','Deep Impact','1998','1','120');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('192','Mulan','1998','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('193','Enemy of the State','1998','1','132');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('194','The Mask of Zorro','1998','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('195','A Bug''s Life','1998','1','95');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('196','Godzilla','1998','1','139');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('197','Armageddon','1998','1','151');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('198','Lethal Weapon 4','1998','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('199','The Blair Witch Project','1999','1','81');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('200','American Pie','1999','1','95');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('201','American Beauty','1999','1','122');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('202','Big Daddy','1999','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('203','The Sixth Sense','1999','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('204','Notting Hill','1999','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('205','The General''s Daughter','1999','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('206','The Green Mile','1999','1','189');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('207','The Matrix','1999','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('208','Runaway Bride','1999','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('209','Double Jeopardy','1999','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('210','Analyze This','1999','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('211','The Mummy','1999','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('212','Toy Story 2','1999','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('213','Star Wars: Episode I - The Phantom Menace','1999','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('214','Stuart Little','1999','1','84');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('215','The World Is Not Enough','1999','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('216','Tarzan','1999','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('217','Wild Wild West','1999','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('218','Crouching Tiger Hidden Dragon"','2000','1','120');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('219','Scary Movie','2000','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('220','Big Momma''s House','2000','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('221','Remember the Titans','2000','1','113');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('222','Chicken Run','2000','1','84');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('223','Traffic','2000','1','147');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('224','Erin Brockovich','2000','1','131');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('225','Meet the Parents','2000','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('226','What Women Want','2000','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('227','X-Men','2000','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('228','Nutty Professor II: The Klumps','2000','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('229','Cast Away','2000','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('230','Charlie''s Angels','2000','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('231','What Lies Beneath','2000','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('232','Gladiator','2000','1','155');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('233','The Patriot','2000','1','165');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('234','The Perfect Storm','2000','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('235','How the Grinch Stole Christmas','2000','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('236','Mission: Impossible II','2000','1','123');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('237','Dinosaur','2000','1','82');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('238','American Pie 2','2001','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('239','Spy Kids','2001','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('240','The Princess Diaries','2001','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('241','The Fast and the Furious','2001','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('242','Shrek','2001','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('243','A Beautiful Mind','2001','1','135');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('244','Vanilla Sky','2001','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('245','Dr. Dolittle 2','2001','1','87');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('246','Ocean''s Eleven','2001','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('247','Hannibal','2001','1','131');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('248','Rush Hour 2','2001','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('249','Black Hawk Down','2001','1','144');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('250','Jurassic Park III','2001','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('251','TLR : The Fellowship of the Ring','2001','1','178');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('252','The Mummy Returns','2001','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('253','Planet of the Apes','2001','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('254','Lara Croft: Tomb Raider','2001','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('255','"Monsters Inc.','2001','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('256','Harry Potter and the Sorcerer''s Stone','2001','1','152');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('257','Pearl Harbor','2001','1','183');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('258','My Big Fat Greek Wedding','2002','1','95');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('259','Sweet Home Alabama','2002','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('260','The Ring','2002','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('261','Mr. Deeds','2002','1','96');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('262','Ice Age','2002','1','81');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('263','The Bourne Identity','2002','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('264','Austin Powers in Goldmember','2002','1','94');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('265','The Santa Clause 2','2002','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('266','xXx','2002','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('267','Signs','2002','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('268','The Lord of the Rings: The Two Towers','2002','1','179');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('269','Lilo & Stitch','2002','1','85');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('270','Scooby-Doo','2002','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('271','Harry Potter and the Chamber of Secrets','2002','1','161');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('272','Minority Report','2002','1','145');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('273','Star Wars: Episode II - Attack of the Clones','2002','1','142');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('274','Spider-Man','2002','1','121');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('275','Men in Black 2','2002','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('276','Die Another Day','2002','1','133');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('277','Bringing Down the House','2003','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('278','Elf','2003','1','97');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('279','Spy Kids 3-D: Game Over','2003','1','84');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('280','Cheaper by the Dozen','2003','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('281','Anger Management','2003','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('282','2 Fast 2 Furious','2003','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('283','Bruce Almighty','2003','1','101');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('284','S.W.A.T.','2003','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('285','Something''s Gotta Give','2003','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('286','Seabiscuit','2003','1','141');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('287','Finding Nemo','2003','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('288','The Lord of the Rings: The Return of the King','2003','1','201');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('289','X2: X-Men United','2003','1','133');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('290','Bad Boys II','2003','1','147');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('291','Hulk','2003','1','138');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('292','Pirates of the Caribbean: The Curse of the Black Pearl','2003','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('293','The Last Samurai','2003','1','154');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('294','The Matrix Reloaded','2003','1','138');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('295','The Matrix Revolutions','2003','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('296','Terminator 3: Rise of the Machines','2003','1','109');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('297','Fahrenheit 9/11','2004','1','122');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('298','DodgeBall: A True Underdog Story','2004','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('299','The Passion of the Christ','2004','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('300','The Village','2004','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('301','50 First Dates','2004','1','99');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('302','The Bourne Supremacy','2004','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('303','Shark Tale','2004','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('304','Meet the Fockers','2004','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('305','The Incredibles','2004','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('306','National Treasure','2004','1','131');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('307','Ocean''s Twelve','2004','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('308','"I',' Robot"','2004','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('309','The Day After Tomorrow','2004','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('310','Harry Potter and the Prisoner of Azkaban','2004','1','141');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('311','Lemony Snicket''s A Series of Unfortunate Events','2004','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('312','Shrek 2','2004','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('313','Van Helsing','2004','1','132');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('314','The Polar Express','2004','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('315','Troy','2004','1','163');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('316','Spider-Man 2','2004','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('317','The 40 Year Old Virgin','2005','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('318','Walk the Line','2005','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('319','Wedding Crashers','2005','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('320','Flightplan','2005','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('321','The Pacifier','2005','1','95');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('322','Hitch','2005','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('323','Robots','2005','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('324','Madagascar','2005','1','86');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('325','The Longest Yard','2005','1','113');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('326','Fantastic Four','2005','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('327','Fun with Dick and Jane','2005','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('328','Mr. & Mrs. Smith','2005','1','120');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('329','Star Wars: Episode III - Revenge of the Sith','2005','1','140');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('330','War of the Worlds','2005','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('331','Batman Begins','2005','1','140');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('332','Charlie and the Chocolate Factory','2005','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('333','Chicken Little','2005','1','81');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('334','Harry Potter and the Goblet of Fire','2005','1','157');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('335','"The Chronicles of Narnia: The Lion,the Witch and the Wardrobe','2005','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('336','King Kong','2005','1','187');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('337','Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan','2006','1','82');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('338','The Devil Wears Prada','2006','1','109');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('339','Scary Movie 4','2006','1','83');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('340','The Break-Up','2006','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('341','The Pursuit of Happyness','2006','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('342','Dreamgirls','2006','1','134');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('343','Talladega Nights: The Ballad of Ricky Bobby','2006','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('344','Ice Age: The Meltdown','2006','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('345','Over the Hedge','2006','1','83');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('346','Click','2006','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('347','The Departed','2006','1','151');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('348','Happy Feet','2006','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('349','Night at the Museum','2006','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('350','Cars','2006','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('351','The Da Vinci Code','2006','1','149');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('352','Mission: Impossible III','2006','1','126');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('353','Casino Royale','2006','1','144');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('354','Pirates of the Caribbean: Dead Man''s Chest','2006','1','151');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('355','X-Men: The Last Stand','2006','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('356','Superman Returns','2006','1','154');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('357','Juno','2007','1','96');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('358','Knocked Up','2007','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('359','Wild Hogs','2007','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('360','300','2007','1','155');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('361','Alvin and the Chipmunks','2007','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('362','The Bourne Ultimatum','2007','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('363','The Simpsons Movie','2007','1','87');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('364','Enchanted','2007','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('365','American Gangster','2007','1','157');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('366','Live Free or Die Hard','2007','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('367','Fantastic 4: Rise of the Silver Surfer','2007','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('368','National Treasure: Book of Secrets','2007','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('369','Rush Hour 3','2007','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('370','Ratatouille','2007','1','111');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('371','Transformers','2007','1','144');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('372','Harry Potter and the Order of the Phoenix','2007','1','138');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('373','I Am Legend','2007','1','101');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('374','Shrek the Third','2007','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('375','Spider-Man 3','2007','1','139');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('376','Pirates of the Caribbean: At World''s End','2007','1','169');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('377','Slumdog Millionaire','2008','1','120');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('378','Gran Torino','2008','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('379','Twilight','2008','1','122');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('380','Mamma Mia!','2008','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('381','Marley and Me','2008','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('382','Sex and the City','2008','1','145');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('383','Wanted','2008','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('384','Get Smart','2008','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('385','Horton Hears a Who!','2008','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('386','Kung Fu Panda','2008','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('387','Iron Man','2008','1','126');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('388','The Incredible Hulk','2008','1','114');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('389','Hancock','2008','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('390','Madagascar: Escape 2 Africa','2008','1','89');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('391','The Curious Case of Benjamin Button','2008','1','166');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('392','WALL-E','2008','1','97');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('393','Indiana Jones and the Kingdom of the Crystal Skull','2008','1','122');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('394','The Dark Knight','2008','1','152');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('395','Quantum of Solace','2008','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('396','The Chronicles of Narnia: Prince Caspian','2008','1','150');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('397','Taken','2009','1','90');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('398','Paul Blart: Mall Cop','2009','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('399','The Blind Side','2009','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('400','The Hangover','2009','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('401','The Proposal','2009','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('402','The Twilight Saga: New Moon','2009','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('403','Alvin and the Chipmunks: The Squeakquel','2009','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('404','Fast and Furious','2009','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('405','Ice Age: Dawn of the Dinosaurs','2009','1','94');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('406','Sherlock Holmes','2009','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('407','X-Men Origins: Wolverine','2009','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('408','Star Trek','2009','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('409','Night at the Museum: Battle of the Smithsonian','2009','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('410','Transformers: Revenge of the Fallen','2009','1','150');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('411','Monsters vs Aliens','2009','1','94');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('412','Up','2009','1','96');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('413','G.I. Joe: The Rise of Cobra','2009','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('414','2012','2009','1','158');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('415','Avatar','2009','1','162');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('416','Harry Potter and the Half-Blood Prince','2009','1','153');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('417','The King''s Speech','2010','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('418','True Grit','2010','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('419','The Karate Kid','2010','1','140');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('420','The Twilight Saga: Eclipse','2010','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('421','Despicable Me','2010','1','95');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('422','Shutter Island','2010','1','138');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('423','Grown Ups','2010','1','102');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('424','Little Fockers','2010','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('425','Clash of the Titans','2010','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('426','Megamind','2010','1','95');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('427','The Last Airbender','2010','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('428','Inception','2010','1','148');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('429','How to Train Your Dragon','2010','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('430','Shrek Forever After','2010','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('431','Tron Legacy','2010','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('432','Alice in Wonderland','2010','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('433','Iron Man 2','2010','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('434','Toy Story 3','2010','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('435','Harry Potter and the Deathly Hallows: Part 1','2010','1','146');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('436','Tangled','2010','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('437','The Help','2011','1','146');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('438','Bridesmaids','2011','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('439','Alvin and the Chipmunks: Chipwrecked','2011','1','87');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('440','The Hangover Part II','2011','1','102');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('441','Rio','2011','1','96');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('442','Rise of the Planet of the Apes','2011','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('443','The Twilight Saga: Breaking Dawn - Part 1','2011','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('444','The Smurfs','2011','1','103');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('445','Fast Five','2011','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('446','Harry Potter and the Deathly Hallows: Part 2','2011','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('447','Sherlock Holmes: A Game of Shadows','2011','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('448','Puss in Boots: The Three Diablos','2011','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('449','Captain America: The First Avenger','2011','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('450','Mission: Impossible - Ghost Protocol','2011','1','133');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('451','Thor','2011','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('452','Kung Fu Panda 2','2011','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('453','Transformers: Dark of the Moon','2011','1','154');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('454','Cars 2','2011','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('455','Pirates of the Caribbean: On Stranger Tides','2011','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('456','Taken 2','2012','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('457','Ted','2012','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('458','Les Miserables','2012','1','158');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('459','Lincoln','2012','1','149');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('460','The Lorax','2012','1','86');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('461','The Hunger Games','2012','1','142');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('462','Hotel Transylvania','2012','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('463','Ice Age: Continental Drift','2012','1','88');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('464','Django Unchained','2012','1','165');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('465','The Twilight Saga: Breaking Dawn - Part 2','2012','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('466','Madagascar 3: Europe''s Most Wanted','2012','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('467','Wreck-It Ralph','2012','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('468','Snow White and the Huntsman','2012','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('469','Brave','2012','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('470','Skyfall','2012','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('471','The Amazing Spider-Man','2012','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('472','The Avengers','2012','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('473','Men in Black 3','2012','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('474','The Dark Knight Rises','2012','1','165');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('475','The Hobbit: An Unexpected Journey','2012','1','169');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('476','The Conjuring','2013','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('477','Identity Thief','2013','1','111');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('478','We''re The Millers','2013','1','110');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('479','American Hustle','2013','1','138');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('480','The Heat','2013','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('481','Despicable Me 2','2013','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('482','The Great Gatsby','2013','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('483','Gravity','2013','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('484','The Hunger Games: Catching Fire','2013','1','146');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('485','The Croods','2013','1','98');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('486','Frozen','2013','1','102');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('487','Fast & Furious 6','2013','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('488','Thor: The Dark World','2013','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('489','Star Trek Into Darkness','2013','1','132');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('490','Oz: The Great and Powerful','2013','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('491','Iron Man 3','2013','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('492','World War Z','2013','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('493','Monsters University','2013','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('494','Man of Steel','2013','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('495','The Hobbit: The Desolation of Smaug','2013','1','161');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('496','Neighbors','2014','1','96');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('497','22 Jump Street','2014','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('498','American Sniper','2014','1','133');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('499','The Lego Movie','2014','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('500','Gone Girl','2014','1','145');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('501','Divergent','2014','1','139');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('502','Teenage Mutant Ninja Turtles','2014','1','101');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('503','The Hunger Games: Mockingjay - Part 1','2014','1','123');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('504','How to Train Your Dragon 2','2014','1','102');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('505','Godzilla','2014','1','123');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('506','Big Hero 6','2014','1','102');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('507','Interstellar','2014','1','169');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('508','Captain America: The Winter Soldier','2014','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('509','Dawn of the Planet of the Apes','2014','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('510','Guardians of the Galaxy','2014','1','121');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('511','Maleficent','2014','1','97');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('512','The Amazing Spider-Man 2','2014','1','142');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('513','Transformers: Age of Extinction','2014','1','165');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('514','X-Men: Days of Future Past','2014','1','131');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('515','The Hobbit: The Battle of the Five Armies','2014','1','144');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('516','Straight Outta Compton','2015','1','147');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('517','Pitch Perfect 2','2015','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('518','Fifty Shades of Grey','2015','1','125');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('519','The SpongeBob Movie: Sponge Out of Water','2015','1','93');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('520','Minions','2015','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('521','Hotel Transylvania 2','2015','1','89');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('522','Cinderella','2015','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('523','The Martian','2015','1','141');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('524','San Andreas','2015','1','114');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('525','Ant-Man','2015','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('526','Home','2015','1','94');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('527','The Revenant','2015','1','156');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('528','Jurassic World','2015','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('529','Mission: Impossible - Rogue Nation','2015','1','131');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('530','The Hunger Games: Mockingjay - Part 2','2015','1','137');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('531','Inside Out','2015','1','94');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('532','Furious 7','2015','1','137');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('533','Spectre','2015','1','148');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('534','Star Wars: The Force Awakens','2015','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('535','Avengers: Age of Ultron','2015','1','141');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('536','Hidden Figures','2016','1','127');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('537','La La Land','2016','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('538','Deadpool','2016','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('539','The Secret Life of Pets','2016','1','87');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('540','Sing','2016','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('541','Jason Bourne','2016','1','123');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('542','Trolls','2016','1','92');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('543','Ghostbusters','2016','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('544','Zootopia','2016','1','108');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('545','Moana','2016','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('546','Doctor Strange','2016','1','115');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('547','The Jungle Book','2016','1','106');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('548','Suicide Squad','2016','1','123');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('549','X-Men: Apocalypse','2016','1','144');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('550','Fantastic Beasts and Where to Find Them','2016','1','133');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('551','Star Trek Beyond','2016','1','122');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('552','Finding Dory','2016','1','97');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('553','Rogue One: A Star Wars Story','2016','1','133');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('554','Batman v Superman: Dawn of Justice','2016','1','151');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('555','Captain America: Civil War','2016','1','147');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('556','Get Out','2017','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('557','It','2017','1','135');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('558','The LEGO Batman Movie','2017','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('559','Despicable Me 3','2017','1','96');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('560','The Greatest Showman','2017','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('561','Logan','2017','1','137');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('562','Dunkirk','2017','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('563','The Boss Baby','2017','1','97');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('564','Wonder Woman','2017','1','141');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('565','Jumanji: Welcome to the Jungle','2017','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('566','Beauty and the Beast','2017','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('567','Spider-Man: Homecoming','2017','1','133');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('568','Coco','2017','1','105');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('569','Thor: Ragnarok','2017','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('570','Kong: Skull Island','2017','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('571','Guardians of the Galaxy Vol. 2','2017','1','137');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('572','Pirates of the Caribbean: Dead Men Tell No Tales','2017','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('573','The Fate of the Furious','2017','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('574','Justice League','2017','1','120');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('575','Star Wars: The Last Jedi','2019','1','152');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('576','A Quiet Place','2018','1','91');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('577','Crazy Rich Asians','2018','1','121');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('578','A Star is Born','2018','1','135');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('579','Bohemian Rhapsody','2018','1','134');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('580','Dr. Seuss'' The Grinch','2018','1','86');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('581','Hotel Transylvania 3: Summer Vacation','2018','1','97');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('582','Spider-Man: Into the Spider-Verse','2018','1','117');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('583','Deadpool 2','2018','1','119');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('584','Venom','2018','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('585','Mary Poppins Returns','2018','1','130');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('586','Aquaman','2018','1','143');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('587','Jurassic World: Fallen Kingdom','2018','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('588','Ralph Breaks the Internet','2018','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('589','Mission: Impossible - Fallout','2018','1','147');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('590','Ant-Man and the Wasp','2018','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('591','Black Panther','2018','1','134');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('592','Incredibles 2','2018','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('593','Fantanstic Beasts: The Crimes of Grindelwald','2018','1','134');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('594','Solo: A Star Wars Story','2018','1','135');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('595','Avengers: Infinity War','2018','1','149');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('596','Glass','2019','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('597','Us','2019','1','116');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('598','The Upside','2019','1','126');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('599','John Wick: Chapter 3 - Parabellum','2019','1','131');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('600','It: Chapter Two','2019','1','169');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('601','The Secret Life of Pets 2','2019','1','86');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('602','Once Upon a Time in Hollywood','2019','1','161');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('603','The LEGO Movie 2: The Second Part','2019','1','107');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('604','Shazam!','2019','1','132');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('605','How to Train Your Dragon: The Hidden World','2019','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('606','Pokemon Detective Pikachu','2019','1','104');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('607','Spider-Man: Far from Home','2019','1','129');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('608','Dumbo','2019','1','112');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('609','Captain Marvel','2019','1','124');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('610','Aladdin','2019','1','128');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('611','Godzilla: King of the Monsters','2019','1','132');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('612','Toy Story 4','2019','1','100');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('613','Fast & Furious Presents: Hobbs & Shaw','2019','1','136');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('614','The Lion King','2019','1','118');
INSERT INTO film(id_film, titolo, anno_produzione, id_regista, durata_minuti) VALUES ('615','Avengers: Endgame','2019','1','181');


