INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Look Who''s Talking','1989','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Driving Miss Daisy','1989','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Turner & Hooch','1989','1','65','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Born on the Fourth of July','1989','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Field of Dreams','1989','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Uncle Buck','1989','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('When Harry Met Sally...','1989','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dead Poets Society','1989','1','75','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Parenthood','1989','1','75','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lethal Weapon 2','1989','1','75','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The War of the Roses','1989','1','75','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('National Lampoon''s Christmas Vacation','1989','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Honey I Shrunk the Kids','1989','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman','1989','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ghostbusters II','1989','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Little Mermaid','1989','1','83','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Back to the Future Part II','1989','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Indiana Jones and the Last Crusade','1989','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tango & Cash','1989','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Steel Magnolias','1989','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Three Men and a Little Lady','1990','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Teenage Mutant Ninja Turtles','1990','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pretty Woman','1990','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Kindergarten Cop','1990','1','111','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Home Alone','1990','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bird on a Wire','1990','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Misery','1990','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Edward Scissorhands','1990','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ghost','1990','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Presumed Innocent','1990','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dances with Wolves','1990','1','181','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Flatliners','1990','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hunt for Red October','1990','1','134','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Another 48 Hrs.','1990','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Back to the Future Part III','1990','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dick Tracy','1990','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Godfather: Part III','1990','1','162','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Days of Thunder','1990','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Total Recall','1990','1','113','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Die Hard 2','1990','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fried Green Tomatoes','1991','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Silence of the Lambs','1991','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sleeping with the Enemy','1991','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Father of the Bride','1991','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Naked Gun 2 1/2: The Smell of Fear','1991','1','85','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Teenage Mutant Ninja Turtles II','1991','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Beauty and the Beast','1991','1','84','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hot Shots!','1991','1','84','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('City Slickers','1991','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek VI: The Undiscovered Country','1991','1','113','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Addams Family','1991','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Prince of Tides','1991','1','132','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('What About Bob?','1991','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cape Fear','1991','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('JFK','1991','1','189','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Robin Hood: Prince of Thieves','1991','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hook','1991','1','144','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Backdraft','1991','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Terminator 2: Judgment Day','1991','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Crying Game','1992','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hand that Rocks the Cradle','1992','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Unforgiven','1992','1','131','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Home Alone 2: Lost in New York','1992','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wayne''s World','1992','1','94','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Bodyguard','1992','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Aladdin','1992','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('White Men Can''t Jump','1992','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sister Act','1992','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scent of a Woman','1992','1','157','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lethal Weapon 3','1992','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Under Siege','1992','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Boomerang','1992','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A League of Their Own','1992','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Last of the Mohicans','1992','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bram Stoker''s Dracula','1992','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Few Good Men','1992','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Patriot Games','1992','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Basic Instinct','1992','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman Returns','1992','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cool Runnings','1993','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Groundhog Day','1993','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Free Willy','1993','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sleepless in Seattle','1993','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Schindler''s List','1993','1','195','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mrs. Doubtfire','1993','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tombstone','1993','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Philadelphia','1993','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dave','1993','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Grumpy Old Men','1993','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Indecent Proposal','1993','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sister Act 2: Back in the Habit','1993','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('In the Line of Fire','1993','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rising Sun','1993','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Firm','1993','1','154','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Fugitive','1993','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Pelican Brief','1993','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Demolition Man','1993','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cliffhanger','1993','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jurassic Park III','2001','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pulp Fiction','1994','1','154','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ace Ventura: Pet Detective','1994','1','86','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dumb and Dumber','1994','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Santa Clause','1994','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Mask','1994','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Speed','1994','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Legends of the Fall','1994','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek: Generations','1994','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lion King','1994','1','89','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Client','1994','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Specialist','1994','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Flintstones','1994','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Forrest Gump','1994','1','142','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Stargate','1994','1','121','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Disclosure','1994','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Interview with the Vampire','1994','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Clear and Present Danger','1994','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wolf','1994','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Maverick','1994','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('True Lies','1994','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('While You Were Sleeping','1995','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dangerous Minds','1995','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Grumpier Old Men','1995','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Father of the Bride Part II','1995','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Toy Story','1995','1','81','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ace Ventura: When Nature Calls','1995','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Get Shorty','1995','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mr. Holland''s Opus','1995','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Se7en','1995','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Casper','1995','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Congo','1995','1','109','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Apollo 13','1995','1','140','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Crimson Tide','1995','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pocahontas','1995','1','81','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('GoldenEye','1995','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jumanji','1995','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Braveheart','1995','1','177','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Die Hard: With a Vengeance','1995','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman Forever','1995','1','121','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Waterworld','1995','1','135','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scream','1996','1','111','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The First Wives Club','1996','1','102','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The English Patient','1996','1','162','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Birdcage','1996','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Phenomenon','1996','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Time to Kill','1996','1','149','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek: First Contact','1996','1','111','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Broken Arrow','1996','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jerry Maguire','1996','1','139','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Nutty Professor','1996','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('101 Dalmatians','1996','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Rock','1996','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Independence Day','1996','1','145','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mission: Impossible','1996','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ransom','1996','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Space Jam','1996','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Twister','1996','1','113','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hunchback of Notre Dame','1996','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Eraser','1996','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Michael','1996','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Good Will Hunting','1997','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('I Know What You Did Last Summer','1997','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scream 2','1997','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('My Best Friend''s Wedding','1997','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Liar Liar','1997','1','86','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('As Good as It Gets','1997','1','139','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('George of the Jungle','1997','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lost World: Jurassic Park','1997','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Con Air','1997','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Conspiracy Theory','1997','1','135','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Face/Off','1997','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Flubber','1997','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hercules','1997','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Air Force One','1997','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Men in Black','1997','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Contact','1997','1','150','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tomorrow Never Dies','1997','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman and Robin','1997','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Titanic','1997','1','194','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('There''s Something About Mary','1998','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Waterboy','1998','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shakespeare in Love','1998','1','122','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Rugrats Movie','1998','1','79','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rush Hour','1998','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Stepmom','1998','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Patch Adams','1998','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Truman Show','1998','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('You''ve Got Mail','1998','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Saving Private Ryan','1998','1','169','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Prince of Egypt','1998','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Doctor Dolittle','1998','1','85','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Deep Impact','1998','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mulan','1998','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Enemy of the State','1998','1','132','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Mask of Zorro','1998','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Bug''s Life','1998','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Godzilla','1998','1','139','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Armageddon','1998','1','151','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lethal Weapon 4','1998','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Blair Witch Project','1999','1','81','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('American Pie','1999','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('American Beauty','1999','1','122','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Big Daddy','1999','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Sixth Sense','1999','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Notting Hill','1999','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The General''s Daughter','1999','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Green Mile','1999','1','189','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Matrix','1999','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Runaway Bride','1999','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Double Jeopardy','1999','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Analyze This','1999','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Mummy','1999','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Toy Story 2','1999','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Wars: Episode I - The Phantom Menace','1999','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Stuart Little','1999','1','84','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The World Is Not Enough','1999','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tarzan','1999','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wild Wild West','1999','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Crouching Tiger Hidden Dragon"','2000','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scary Movie','2000','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Big Momma''s House','2000','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Remember the Titans','2000','1','113','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Chicken Run','2000','1','84','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Traffic','2000','1','147','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Erin Brockovich','2000','1','131','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Meet the Parents','2000','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('What Women Want','2000','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('X-Men','2000','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Nutty Professor II: The Klumps','2000','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cast Away','2000','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Charlie''s Angels','2000','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('What Lies Beneath','2000','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Gladiator','2000','1','155','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Patriot','2000','1','165','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Perfect Storm','2000','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('How the Grinch Stole Christmas','2000','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mission: Impossible II','2000','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dinosaur','2000','1','82','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('American Pie 2','2001','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spy Kids','2001','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Princess Diaries','2001','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Fast and the Furious','2001','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shrek','2001','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Beautiful Mind','2001','1','135','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Vanilla Sky','2001','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dr. Dolittle 2','2001','1','87','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ocean''s Eleven','2001','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hannibal','2001','1','131','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rush Hour 2','2001','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Black Hawk Down','2001','1','144','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jurassic Park III','2001','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('TLR : The Fellowship of the Ring','2001','1','178','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Mummy Returns','2001','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Planet of the Apes','2001','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lara Croft: Tomb Raider','2001','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('"Monsters Inc.','2001','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Harry Potter and the Sorcerer''s Stone','2001','1','152','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pearl Harbor','2001','1','183','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('My Big Fat Greek Wedding','2002','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sweet Home Alabama','2002','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Ring','2002','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mr. Deeds','2002','1','96','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ice Age','2002','1','81','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Bourne Identity','2002','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Austin Powers in Goldmember','2002','1','94','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Santa Clause 2','2002','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('xXx','2002','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Signs','2002','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lord of the Rings: The Two Towers','2002','1','179','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lilo & Stitch','2002','1','85','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scooby-Doo','2002','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Harry Potter and the Chamber of Secrets','2002','1','161','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Minority Report','2002','1','145','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Wars: Episode II - Attack of the Clones','2002','1','142','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spider-Man','2002','1','121','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Men in Black 2','2002','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Die Another Day','2002','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bringing Down the House','2003','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Elf','2003','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spy Kids 3-D: Game Over','2003','1','84','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cheaper by the Dozen','2003','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Anger Management','2003','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('2 Fast 2 Furious','2003','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bruce Almighty','2003','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('S.W.A.T.','2003','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Something''s Gotta Give','2003','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Seabiscuit','2003','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Finding Nemo','2003','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lord of the Rings: The Return of the King','2003','1','201','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('X2: X-Men United','2003','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bad Boys II','2003','1','147','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hulk','2003','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pirates of the Caribbean: The Curse of the Black Pearl','2003','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Last Samurai','2003','1','154','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Matrix Reloaded','2003','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Matrix Revolutions','2003','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Terminator 3: Rise of the Machines','2003','1','109','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fahrenheit 9/11','2004','1','122','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('DodgeBall: A True Underdog Story','2004','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Passion of the Christ','2004','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Village','2004','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('50 First Dates','2004','1','99','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Bourne Supremacy','2004','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shark Tale','2004','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Meet the Fockers','2004','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Incredibles','2004','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('National Treasure','2004','1','131','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ocean''s Twelve','2004','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('I Robot','2004','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Day After Tomorrow','2004','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Harry Potter and the Prisoner of Azkaban','2004','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lemony Snicket''s A Series of Unfortunate Events','2004','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shrek 2','2004','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Van Helsing','2004','1','132','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Polar Express','2004','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Troy','2004','1','163','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spider-Man 2','2004','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The 40 Year Old Virgin','2005','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Walk the Line','2005','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wedding Crashers','2005','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Flightplan','2005','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Pacifier','2005','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hitch','2005','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Robots','2005','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Madagascar','2005','1','86','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Longest Yard','2005','1','113','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fantastic Four','2005','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fun with Dick and Jane','2005','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mr. & Mrs. Smith','2005','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Wars: Episode III - Revenge of the Sith','2005','1','140','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('War of the Worlds','2005','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman Begins','2005','1','140','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Charlie and the Chocolate Factory','2005','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Chicken Little','2005','1','81','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Harry Potter and the Goblet of Fire','2005','1','157','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('"The Chronicles of Narnia: The Lion,the Witch and the Wardrobe','2005','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('King Kong','2005','1','187','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan','2006','1','82','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Devil Wears Prada','2006','1','109','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Scary Movie 4','2006','1','83','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Break-Up','2006','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Pursuit of Happyness','2006','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dreamgirls','2006','1','134','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Talladega Nights: The Ballad of Ricky Bobby','2006','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ice Age: The Meltdown','2006','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Over the Hedge','2006','1','83','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Click','2006','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Departed','2006','1','151','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Happy Feet','2006','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Night at the Museum','2006','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cars','2006','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Da Vinci Code','2006','1','149','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mission: Impossible III','2006','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Casino Royale','2006','1','144','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pirates of the Caribbean: Dead Man''s Chest','2006','1','151','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('X-Men: The Last Stand','2006','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Superman Returns','2006','1','154','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Juno','2007','1','96','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Knocked Up','2007','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wild Hogs','2007','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('300','2007','1','155','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Alvin and the Chipmunks','2007','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Bourne Ultimatum','2007','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Simpsons Movie','2007','1','87','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Enchanted','2007','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('American Gangster','2007','1','157','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Live Free or Die Hard','2007','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fantastic 4: Rise of the Silver Surfer','2007','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('National Treasure: Book of Secrets','2007','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rush Hour 3','2007','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ratatouille','2007','1','111','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Transformers','2007','1','144','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Harry Potter and the Order of the Phoenix','2007','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('I Am Legend','2007','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shrek the Third','2007','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spider-Man 3','2007','1','139','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pirates of the Caribbean: At World''s End','2007','1','169','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Slumdog Millionaire','2008','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Gran Torino','2008','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Twilight','2008','1','122','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mamma Mia!','2008','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Marley and Me','2008','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sex and the City','2008','1','145','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wanted','2008','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Get Smart','2008','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Horton Hears a Who!','2008','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Kung Fu Panda','2008','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Iron Man','2008','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Incredible Hulk','2008','1','114','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hancock','2008','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Madagascar: Escape 2 Africa','2008','1','89','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Curious Case of Benjamin Button','2008','1','166','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('WALL-E','2008','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Indiana Jones and the Kingdom of the Crystal Skull','2008','1','122','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Dark Knight','2008','1','152','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Quantum of Solace','2008','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Chronicles of Narnia: Prince Caspian','2008','1','150','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Taken','2009','1','90','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Paul Blart: Mall Cop','2009','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Blind Side','2009','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hangover','2009','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Proposal','2009','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Twilight Saga: New Moon','2009','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Alvin and the Chipmunks: The Squeakquel','2009','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fast and Furious','2009','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ice Age: Dawn of the Dinosaurs','2009','1','94','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sherlock Holmes','2009','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('X-Men Origins: Wolverine','2009','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek','2009','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Night at the Museum: Battle of the Smithsonian','2009','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Transformers: Revenge of the Fallen','2009','1','150','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Monsters vs Aliens','2009','1','94','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Up','2009','1','96','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('G.I. Joe: The Rise of Cobra','2009','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('2012','2009','1','158','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Avatar','2009','1','162','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Harry Potter and the Half-Blood Prince','2009','1','153','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The King''s Speech','2010','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('True Grit','2010','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Karate Kid','2010','1','140','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Twilight Saga: Eclipse','2010','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Despicable Me','2010','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shutter Island','2010','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Grown Ups','2010','1','102','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Little Fockers','2010','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Clash of the Titans','2010','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Megamind','2010','1','95','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Last Airbender','2010','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Inception','2010','1','148','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('How to Train Your Dragon','2010','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shrek Forever After','2010','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tron Legacy','2010','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Alice in Wonderland','2010','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Iron Man 2','2010','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Toy Story 3','2010','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Harry Potter and the Deathly Hallows: Part 1','2010','1','146','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Tangled','2010','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Help','2011','1','146','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bridesmaids','2011','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Alvin and the Chipmunks: Chipwrecked','2011','1','87','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hangover Part II','2011','1','102','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rio','2011','1','96','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rise of the Planet of the Apes','2011','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Twilight Saga: Breaking Dawn - Part 1','2011','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Smurfs','2011','1','103','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fast Five','2011','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Harry Potter and the Deathly Hallows: Part 2','2011','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sherlock Holmes: A Game of Shadows','2011','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Puss in Boots: The Three Diablos','2011','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Captain America: The First Avenger','2011','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mission: Impossible - Ghost Protocol','2011','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Thor','2011','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Kung Fu Panda 2','2011','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Transformers: Dark of the Moon','2011','1','154','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cars 2','2011','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pirates of the Caribbean: On Stranger Tides','2011','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Taken 2','2012','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ted','2012','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Les Miserables','2012','1','158','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Lincoln','2012','1','149','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lorax','2012','1','86','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hunger Games','2012','1','142','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hotel Transylvania','2012','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ice Age: Continental Drift','2012','1','88','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Django Unchained','2012','1','165','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Twilight Saga: Breaking Dawn - Part 2','2012','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Madagascar 3: Europe''s Most Wanted','2012','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wreck-It Ralph','2012','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Snow White and the Huntsman','2012','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Brave','2012','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Skyfall','2012','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Amazing Spider-Man','2012','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Avengers','2012','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Men in Black 3','2012','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Dark Knight Rises','2012','1','165','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hobbit: An Unexpected Journey','2012','1','169','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Conjuring','2013','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Identity Thief','2013','1','111','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('We''re The Millers','2013','1','110','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('American Hustle','2013','1','138','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Heat','2013','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Despicable Me 2','2013','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Great Gatsby','2013','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Gravity','2013','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hunger Games: Catching Fire','2013','1','146','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Croods','2013','1','98','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Frozen','2013','1','102','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fast & Furious 6','2013','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Thor: The Dark World','2013','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek Into Darkness','2013','1','132','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Oz: The Great and Powerful','2013','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Iron Man 3','2013','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('World War Z','2013','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Monsters University','2013','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Man of Steel','2013','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hobbit: The Desolation of Smaug','2013','1','161','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Neighbors','2014','1','96','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('22 Jump Street','2014','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('American Sniper','2014','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lego Movie','2014','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Gone Girl','2014','1','145','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Divergent','2014','1','139','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Teenage Mutant Ninja Turtles','2014','1','101','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hunger Games: Mockingjay - Part 1','2014','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('How to Train Your Dragon 2','2014','1','102','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Godzilla','2014','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Big Hero 6','2014','1','102','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Interstellar','2014','1','169','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Captain America: The Winter Soldier','2014','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dawn of the Planet of the Apes','2014','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Guardians of the Galaxy','2014','1','121','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Maleficent','2014','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Amazing Spider-Man 2','2014','1','142','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Transformers: Age of Extinction','2014','1','165','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('X-Men: Days of Future Past','2014','1','131','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hobbit: The Battle of the Five Armies','2014','1','144','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Straight Outta Compton','2015','1','147','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pitch Perfect 2','2015','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fifty Shades of Grey','2015','1','125','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The SpongeBob Movie: Sponge Out of Water','2015','1','93','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Minions','2015','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hotel Transylvania 2','2015','1','89','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Cinderella','2015','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Martian','2015','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('San Andreas','2015','1','114','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ant-Man','2015','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Home','2015','1','94','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Revenant','2015','1','156','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jurassic World','2015','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mission: Impossible - Rogue Nation','2015','1','131','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Hunger Games: Mockingjay - Part 2','2015','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Inside Out','2015','1','94','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Furious 7','2015','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spectre','2015','1','148','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Wars: The Force Awakens','2015','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Avengers: Age of Ultron','2015','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hidden Figures','2016','1','127','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('La La Land','2016','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Deadpool','2016','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Secret Life of Pets','2016','1','87','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Sing','2016','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jason Bourne','2016','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Trolls','2016','1','92','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ghostbusters','2016','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Zootopia','2016','1','108','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Moana','2016','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Doctor Strange','2016','1','115','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Jungle Book','2016','1','106','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Suicide Squad','2016','1','123','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('X-Men: Apocalypse','2016','1','144','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fantastic Beasts and Where to Find Them','2016','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Trek Beyond','2016','1','122','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Finding Dory','2016','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Rogue One: A Star Wars Story','2016','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Batman v Superman: Dawn of Justice','2016','1','151','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Captain America: Civil War','2016','1','147','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Get Out','2017','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('It','2017','1','135','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The LEGO Batman Movie','2017','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Despicable Me 3','2017','1','96','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Greatest Showman','2017','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Logan','2017','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dunkirk','2017','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Boss Baby','2017','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Wonder Woman','2017','1','141','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jumanji: Welcome to the Jungle','2017','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Beauty and the Beast','2017','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spider-Man: Homecoming','2017','1','133','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Coco','2017','1','105','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Thor: Ragnarok','2017','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Kong: Skull Island','2017','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Guardians of the Galaxy Vol. 2','2017','1','137','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pirates of the Caribbean: Dead Men Tell No Tales','2017','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Fate of the Furious','2017','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Justice League','2017','1','120','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Star Wars: The Last Jedi','2019','1','152','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Quiet Place','2018','1','91','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Crazy Rich Asians','2018','1','121','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('A Star is Born','2018','1','135','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Bohemian Rhapsody','2018','1','134','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dr. Seuss'' The Grinch','2018','1','86','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Hotel Transylvania 3: Summer Vacation','2018','1','97','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spider-Man: Into the Spider-Verse','2018','1','117','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Deadpool 2','2018','1','119','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Venom','2018','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mary Poppins Returns','2018','1','130','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Aquaman','2018','1','143','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Jurassic World: Fallen Kingdom','2018','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ralph Breaks the Internet','2018','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Mission: Impossible - Fallout','2018','1','147','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Ant-Man and the Wasp','2018','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Black Panther','2018','1','134','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Incredibles 2','2018','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fantanstic Beasts: The Crimes of Grindelwald','2018','1','134','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Solo: A Star Wars Story','2018','1','135','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Avengers: Infinity War','2018','1','149','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Glass','2019','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Us','2019','1','116','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Upside','2019','1','126','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('John Wick: Chapter 3 - Parabellum','2019','1','131','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('It: Chapter Two','2019','1','169','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Secret Life of Pets 2','2019','1','86','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Once Upon a Time in Hollywood','2019','1','161','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The LEGO Movie 2: The Second Part','2019','1','107','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Shazam!','2019','1','132','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('How to Train Your Dragon: The Hidden World','2019','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Pokemon Detective Pikachu','2019','1','104','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Spider-Man: Far from Home','2019','1','129','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Dumbo','2019','1','112','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Captain Marvel','2019','1','124','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Aladdin','2019','1','128','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Godzilla: King of the Monsters','2019','1','132','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Toy Story 4','2019','1','100','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Fast & Furious Presents: Hobbs & Shaw','2019','1','136','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('The Lion King','2019','1','118','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Avengers: Endgame','2019','1','181','');
INSERT INTO film( titolo, anno_produzione, id_regista, durata_minuti,url_poster) VALUES ('Marte Nera: Endgame','2021','1','181','');

