INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Travolta','1954-02-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kirstie Alley','1951-01-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Olympia Dillakis','1931-06-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('George Segal','1934-02-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Abe Vigoda','1921-02-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bruce Willis','1955-03-19','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Twink Caplan','1947-12-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Schaller','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jaryd Waterhouse','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Morgan Freeman','1937-06-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jessica Tandy','1909-06-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dan Aykroyd','1952-07-01','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patti LuPone','1949-04-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Esther Rolle','1920-11-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jo Ann Havrilla','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('William Hall Jr.','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alvin M. Sugarman','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Clarice F. Geigerman','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Cruise','1962-07-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bryan Larkin','1973-08-07','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Raymond J. Barry','1939-03-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Caroline Kava','1949-09-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Josh Evans','1971-01-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Seth Allen','1941-07-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jamie Talisman','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Stone','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Anne Bobby','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kevin Costner','1955-01-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Amy Madigan','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gaby Hoffmann','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ray Liotta','1954-12-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Timothy Busfield','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Earl Jones','1931-01-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Burt Lancaster','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Frank Whaley','1963-07-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dwier Brown','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Candy','1950-10-31','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jean Louisa Kelly','1972-03-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Macaulay Culkin','1980-08-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elaine Bromka','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Garrett M. Brown','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Laurie Metcalf','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jay Underwood','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Crystal','1948-03-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Meg Ryan','1961-11-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Carrie Fisher','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bruno Kirby','1949-04-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Steven Ford','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lisa Jane Persky','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michelle Nicastro','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gretchen Palmer','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Alan Beuth','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robin Williams','1951-07-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Sean Leonard','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ethan Hawke','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Josh Charles','1971-09-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gale Hansen','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dylan Kussman','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Allelon Ruggiero','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Waterston','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Norman Lloyd','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Steve Martin','1945-08-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mary Steenburgen','1953-02-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dianne Wiest','1948-03-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Robards','1992-07-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rick Moranis','1953-04-18','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Hulce','1953-12-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Martha Plimpton','1960-11-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Keanu Reeves','1964-09-02','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harley Jane Kozak','1957-01-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Mel Gibson','1956-01-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Danny Glover','1946-07-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joe Pesci','1943-02-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joss Ackland','1928-02-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Derrick O''Connor','1941-01-03','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Patsy Kensit','1968-03-04','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Darlene Love','1938-07-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Traci Wolfe','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Steve Kahan','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Douglas','1944-09-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kathleen Turner','1954-06-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Danny DeVito','1944-11-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Marianne Sgebrecht','1944-11-17','67');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Astin','1971-02-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Heather Fairfield','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('G.D. Spradlin','1920-08-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter Donat','1960-12-11','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dan Castellaneta','1957-10-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Chevy Chase','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Beverly D''Angelo','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Juliette Lewis','1973-06-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Johnny Galecki','1975-04-30','Belgium');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Randolph','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Diane Ladd','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('E.G. Marshall','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Doris Roberts','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Randy Quaid','1950-10-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Matt Frewer','1958-01-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Marcia Strassman','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kristine Sutherland','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Thomas Wilson Brown','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jared Rushton','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Amy O''Neill','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Oliveri','1978-04-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Carl Steven','1960-12-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Keaton','1951-09-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jack Nicholson','1937-04-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kim Basinger','1953-12-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robert Wuhl','1951-10-09','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Pat Hingle','1924-07-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Dee Williams','1937-04-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Gough','1916-11-23','British Malaya');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jack Palance','1920-02-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jerry Hall','1956-07-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bill Murray','1950-09-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sigourney Weaver','1949-10-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harold Ramis','1944-11-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ernie Hudson','1945-12-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Annie Potts','1952-10-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Peter MacNicol','1954-04-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harris Yulin','1937-11-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Rene Auberjonois','1940-06-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher Daniel Barnes','1972-11-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jodi Benson','1961-10-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Pat Carroll','1927-05-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Paddi Edwards','1931-03-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Buddy Hackett','1924-08-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Marin','1974-07-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kenneth Mars','1935-04-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Edie McClurg','1945-07-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael J. Fox','1961-06-09','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christopher Lloyd','1938-10-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lea Thompson','1961-05-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Thomas F. Wilson','1959-04-15','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elisabeth Shue','1963-10-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Tolkan','1931-06-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeffrey Weissman','1958-10-02','');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Casey Siemaszko','1961-03-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Billy Zane','1966-02-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harrison Ford','1942-07-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sean Connery','1930-08-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Denholm Elliott','1922-05-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alison Doody','1966-11-11','Ireland');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Rhys-Davies','1944-05-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Julian Glover','1935-03-27','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('River Phoenix','1970-08-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michael Byrne','1943-11-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sally Field','1946-11-06','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dolly Parton','1946-01-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Shirley MacLaine','1934-04-24','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Daryl Hannah','1960-12-03','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Julia Roberts','1967-10-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Tom Skerritt','1933-08-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Sam Shepard','1943-11-05','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Dylan McDermott','1961-10-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Judith Hoag','1968-06-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elias Koteas','1961-03-11','33');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Josh Pais','1958-06-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Brian Tochi','1959-05-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Leif Tilden','1964-03-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Corey Feldman','1971-07-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Michelan Sisti','1949-05-27','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Robbie Rist','1964-04-04','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Gere','1949-08-31','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Ralph Bellamy','1904-06-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jason Alexander','1959-09-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Laura San Giacomo','1962-11-14','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alex Hyde-White','1959-01-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Amy Yasbeck','1962-09-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Elinor Donahue','1937-04-19','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Hector Elizondo','1936-12-22','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Arnold Schwarzenegger','1947-07-30','9');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Penelope Ann Miller','1964-01-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Pamela Reed','1949-04-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Linda Hunt','1945-04-02','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Tyson','1961-02-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Carroll Baker','1931-05-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joseph Cousins','1983-03-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Christian Cousins','1983-03-17','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Cathy Moriarty','1960-11-29','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Daniel Stern','1957-08-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('John Heard','1946-03-07','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Roberts Blossom','1924-03-25','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Angela Goethals','1977-05-20','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Devin Ratray','1977-01-11','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Gerry Bamman','1941-09-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Goldie Hawn','1945-11-21','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('David Carradine','1936-12-08','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Bill Dille','1943-02-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Stephen Tobolowsky','1951-05-30','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Joan Severance','1958-12-23','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Harry Caesar','1928-02-18','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Jeff Corey','1914-08-10','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Alex Bruhanski','1999-12-12','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('James Caan','1940-03-26','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Kathy Bates','1948-06-28','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Richard Farnsworth','1920-09-01','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Frances Sternhagen','1930-01-13','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Lauren Bacall','1924-09-16','144');
INSERT INTO attori(	 nominativo, data_nascita,paese_di_origine)	VALUES ('Graham Jarvis','1930-08-25','33');


