INSERT INTO TECNOLOGIE_PROIEZIONE(ANNO,TECNOLOGIA)VALUES ('1973','IMAX Dome');
INSERT INTO TECNOLOGIE_PROIEZIONE(ANNO,TECNOLOGIA)VALUES ('2012','IMAX 3D');
INSERT INTO TECNOLOGIE_PROIEZIONE(ANNO,TECNOLOGIA)VALUES ('1992','IMAX HD');
INSERT INTO TECNOLOGIE_PROIEZIONE(ANNO,TECNOLOGIA)VALUES ('2008','IMAX Digitale');
INSERT INTO TECNOLOGIE_PROIEZIONE(ANNO,TECNOLOGIA)VALUES ('2014','IMAX Laser');
INSERT INTO TECNOLOGIE_PROIEZIONE(ANNO,TECNOLOGIA)VALUES ('2011','IMAX 3D Digital Camera');
INSERT INTO TECNOLOGIE_PROIEZIONE(ANNO,TECNOLOGIA)VALUES ('2015','ARRI ALEXA IMAX');